import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {FolderPlus,Download,Upload,Trash2,Undo2,Check,ExternalLink,FileText,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {CASEBOOK_KEY,CASEBOOK_MAX_BYTES,CASEBOOK_LIMITS,newCasebook,createCaseFolder,updateCaseFolder,addCaseEvidence,updateEvidenceNote,parseCasebook,verifyCasebook,importCasebook,mergeCasebooks,writeCasebook,compareEvidence,exportCasebookJSON,exportCaseMarkdown,exportCaseHTML,safeEvidenceURL,type Casebook,type CaseFolder,type CaseEvidence,type EvidenceVersion,type EvidenceComparison} from '../lib/casebook';
import './casebook.css';

type Commit=(next:Casebook)=>void;
type FolderDraft=Pick<CaseFolder,'name'|'notes'|'questions'>;
type CasebookContextValue={book:Casebook;selected:string;select:(id:string)=>void;ready:boolean;error:string;commit:Commit;notice:string;notify:(s:string)=>void;folderDrafts:Map<string,FolderDraft>;entryDrafts:Map<string,string>;setFolderDraft:(id:string,draft:FolderDraft|null)=>void;setEntryDraft:(id:string,draft:string|null)=>void};
const CasebookContext=createContext<CasebookContextValue|null>(null);
export function useCasebook(){const value=useContext(CasebookContext);if(!value)throw Error('CasebookProvider is required');return value;}
export function CasebookProvider({children}:{children:ReactNode}){
 const [book,setBook]=useState<Casebook>(newCasebook),[selected,select]=useState(''),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,notify]=useState('');
 const [folderDrafts,setFolderDrafts]=useState(new Map<string,FolderDraft>()),[entryDrafts,setEntryDrafts]=useState(new Map<string,string>());
 const setFolderDraft=(id:string,draft:FolderDraft|null)=>setFolderDrafts(previous=>{const next=new Map(previous);if(draft===null)next.delete(id);else next.set(id,draft);return next;});
 const setEntryDraft=(id:string,draft:string|null)=>setEntryDrafts(previous=>{const next=new Map(previous);if(draft===null)next.delete(id);else next.set(id,draft);return next;});
 useEffect(()=>{if(!folderDrafts.size&&!entryDrafts.size)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[folderDrafts.size,entryDrafts.size]);
 const raw=useRef<string|null>(null),current=useRef(book),loaded=useRef(false),generation=useRef(0);
 useEffect(()=>{
  let active=true;
  async function load(){const version=++generation.current;loaded.current=false;setReady(false);try{const value=localStorage.getItem(CASEBOOK_KEY),next=value===null?newCasebook():parseCasebook(value);await verifyCasebook(next);if(!active||version!==generation.current)return;raw.current=value;current.current=next;setBook(next);select(id=>next.folders.some(f=>f.id===id)?id:next.folders[0]?.id||'');setError('');loaded.current=true;setReady(true);}catch(e){if(!active||version!==generation.current)return;setError('既有案件無法讀取，已停止寫入以保留原資料。'+errorMessage(e));}}
  void load();const changed=(event:StorageEvent)=>{if(event.key===CASEBOOK_KEY||event.key===null){notify('案件儲存區已在其他分頁變動，已重新讀取。');void load();}};window.addEventListener('storage',changed);
  return()=>{active=false;window.removeEventListener('storage',changed);};
 },[]);
 const commit:Commit=next=>{if(!loaded.current)throw Error('案件儲存區尚未就緒，未寫入。');try{const value=writeCasebook(localStorage,next,raw.current);raw.current=value;current.current=next;setBook(next);setError('');}catch(e){setError(errorMessage(e));throw e;}};
 return <CasebookContext.Provider value={{book,selected,select,ready,error,commit,notice,notify,folderDrafts,entryDrafts,setFolderDraft,setEntryDraft}}>{children}</CasebookContext.Provider>;
}
function errorMessage(e:unknown){return e instanceof Error?e.message:String(e);}
export function downloadCaseFile(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'-');document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function AddEvidenceButton({makeEvidence,label='加入案件',title,disabled=false,className=''}:{makeEvidence:()=>Promise<CaseEvidence>|CaseEvidence;label?:string;title?:string;disabled?:boolean;className?:string}){
 const ctx=useCasebook(),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[draft,setDraft]=useState<CaseEvidence|null>(null),[message,setMessage]=useState(''),[problem,setProblem]=useState(''),[folderId,setFolderId]=useState(''),[name,setName]=useState(''),[note,setNote]=useState('');
 const trigger=useRef<HTMLButtonElement>(null),run=useRef(0);
 useEffect(()=>()=>{run.current++;},[]);
 async function openCapture(){const attempt=++run.current;setOpen(true);setDraft(null);setProblem('');setMessage('');setBusy(true);setNote('');setName('');setFolderId(ctx.book.folders.some(f=>f.id===ctx.selected)?ctx.selected:ctx.book.folders[0]?.id||'');try{const entry=await makeEvidence();if(attempt===run.current)setDraft(entry);}catch(e){if(attempt===run.current)setProblem(errorMessage(e));}finally{if(attempt===run.current)setBusy(false);}}
 function close(){setOpen(false);run.current++;setBusy(false);}
 function save(){if(!draft)return;try{let next=ctx.book,id=folderId;if(!id){const created=createCaseFolder(next,name);next=created.book;id=created.folder.id;}
   const result=addCaseEvidence(next,id,{...draft,note});if(result.duplicate){setMessage('這份相同版本的引用已在案件中，未重複新增。');close();return;}ctx.commit(result.book);ctx.select(id);const text=`已保存至「${result.book.folders.find(f=>f.id===id)?.name}」。`;ctx.notify(text);setMessage(text);close();
  }catch(e){setProblem(errorMessage(e));}}
 return <><button ref={trigger} type="button" className={'casebook-add '+className} title={title} aria-label={title||label} disabled={disabled||!ctx.ready} onClick={()=>void openCapture()}><FolderPlus size={14}/>{label}</button>{message&&<span className="casebook-inline-status" role="status">{message}</span>}<Dialog open={open} onOpenChange={value=>{if(!value)close();}}><DialogContent className="casebook-capture" showCloseButton={false} onCloseAutoFocus={event=>{event.preventDefault();trigger.current?.focus();}}><div className="casebook-capture-heading"><DialogTitle>加入案件引用</DialogTitle></div><DialogDescription className="sr-only">保存此時的引用文字與來源至本機案件。</DialogDescription><button type="button" className="casebook-capture-close" aria-label="關閉加入案件" onClick={close}><X size={20}/></button>
   {busy?<p role="status">正在保存此版本的原文…</p>:draft&&<><p className="casebook-capture-title">{draft.title}</p><p className="casebook-help">保存引用文字、來源、版本雜湊與頁碼。PDF、表單等原始檔案仍需另行下載。</p><label>存入案件<select value={folderId} onChange={e=>setFolderId(e.target.value)}>{ctx.book.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}<option value="">＋ 建立新案件</option></select></label>{!folderId&&<label>新案件名稱<input autoComplete="off" maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder="例如：板橋店面室內裝修"/></label>}<label>引用註記<textarea rows={3} maxLength={CASEBOOK_LIMITS.note} value={note} onChange={e=>setNote(e.target.value)} placeholder="記錄這筆資料與案件的關係"/></label><div className="casebook-button-row"><button type="button" className="casebook-primary" onClick={save} disabled={!folderId&&!name.trim()}>保存引用</button><button type="button" onClick={close}>取消</button></div></>}{problem&&<p role="alert" className="casebook-error">{problem}</p>}
  </DialogContent></Dialog></>;
}

type Resolver=(entry:CaseEvidence)=>Promise<EvidenceVersion|null>;
const comparisonText:Record<EvidenceComparison,string>={same:'與目前收錄的引用文字相同',changed:'引用文字已有差異，請重新核對', 'source-changed':'引用文字相同，但來源文件版本已變，請核對',unavailable:'目前無法取得相同位置，尚未完成核對'};
function EvidenceCard({entry,folderId,onChoose,resolveCurrent,onRemove}:{entry:CaseEvidence;folderId:string;onChoose?:(entry:CaseEvidence)=>void;resolveCurrent?:Resolver;onRemove:()=>void}){
 const ctx=useCasebook(),draftId=JSON.stringify([folderId,entry.id]),note=ctx.entryDrafts.get(draftId)??entry.note,[problem,setProblem]=useState(''),[busy,setBusy]=useState(false),[comparison,setComparison]=useState<EvidenceComparison|null>(null),[checked,setChecked]=useState<string|null>(null),[confirmRemove,setConfirmRemove]=useState(false);
 const setNote=(text:string)=>ctx.setEntryDraft(draftId,text===entry.note?null:text);
 async function check(){if(!resolveCurrent)return;setBusy(true);setProblem('');try{const current=await resolveCurrent(entry);setComparison(compareEvidence(entry,current));setChecked(new Date().toISOString());}catch{setComparison('unavailable');setChecked(new Date().toISOString());}finally{setBusy(false);}}
 return <article className="casebook-evidence"><div className="casebook-evidence-head"><div><span className="casebook-kind">{entry.kind==='article'?'條文':entry.kind==='ruling'?'函釋':entry.kind==='source'?'官方資料／表單':'文件'} · {entry.region}</span><h3>{entry.title}</h3></div><button type="button" title="移除此筆引用" aria-label={'移除'+entry.title} onClick={()=>setConfirmRemove(v=>!v)}><Trash2 size={15}/></button></div><dl className="casebook-evidence-meta"><dt>保存時間</dt><dd>{entry.capturedAt.slice(0,10)}</dd><dt>來源觀測</dt><dd>{entry.observedAt||'未提供／待核對'}</dd><dt>官方日期</dt><dd>{entry.officialModifiedAt||'未提供／待核對'}</dd><dt>生效日期</dt><dd>{entry.effectiveAt||'未提供／待核對'}</dd>{entry.locator.page&&<><dt>原檔頁碼</dt><dd>{entry.locator.page}</dd></>}</dl>
   <details><summary>檢視保存原文與版本</summary><blockquote>{entry.quote}</blockquote><p className="casebook-hash">原文 SHA-256：{entry.contentHash}<br/>來源內容 SHA-256：{entry.sourceHash||'未提供'}</p></details><div className="casebook-evidence-links">{onChoose&&<button type="button" onClick={()=>onChoose(entry)}><FileText size={14}/>開啟目前收錄版本</button>}<a href={safeEvidenceURL(entry.sourceURL)||undefined} target="_blank" rel="noreferrer"><ExternalLink size={14}/>官方原文</a>{entry.sourcePageURL!==entry.sourceURL&&<a href={safeEvidenceURL(entry.sourcePageURL)||undefined} target="_blank" rel="noreferrer">來源頁面</a>}{resolveCurrent&&<button type="button" disabled={busy} onClick={()=>void check()}>{busy?'核對中…':'核對目前版本'}</button>}</div>
   {comparison&&<p className={'casebook-comparison '+(comparison==='same'?'casebook-ok':'casebook-needs-check')} role="status">{comparisonText[comparison]}。{checked&&<small>核對於 {checked.slice(0,10)}；僅比對本庫收錄資料。保存原文維持不變。</small>}</p>}
   <label>引用註記<textarea rows={2} maxLength={CASEBOOK_LIMITS.note} value={note} onChange={e=>setNote(e.target.value)}/></label>{note!==entry.note&&<><p className="casebook-draft-notice">註記尚未儲存；暫存在本次開啟的網頁中。</p><div className="casebook-button-row"><button type="button" onClick={()=>{try{ctx.commit(updateEvidenceNote(ctx.book,folderId,entry.id,note));ctx.setEntryDraft(draftId,null);ctx.notify('引用註記已儲存。');setProblem('');}catch(e){setProblem(errorMessage(e));}}}>儲存註記</button><button type="button" onClick={()=>ctx.setEntryDraft(draftId,null)}>捨棄註記草稿</button></div></>}{problem&&<p className="casebook-error" role="alert">{problem}</p>}{confirmRemove&&<div className="casebook-confirm"><p>移除這筆引用？移除後可在本次操作中復原。</p><button type="button" onClick={onRemove}>確認移除引用</button><button type="button" onClick={()=>setConfirmRemove(false)}>保留</button></div>}
  </article>;
}

export function CasebookPanel({onChoose,resolveCurrent}:{onChoose?:(entry:CaseEvidence)=>void;resolveCurrent?:Resolver}){
 const ctx=useCasebook(),folder=ctx.book.folders.find(f=>f.id===ctx.selected)||ctx.book.folders[0],file=useRef<HTMLInputElement>(null);
 const [newName,setNewName]=useState(''),[problem,setProblem]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),[undo,setUndo]=useState<{before:Casebook;after:string;label:string}|null>(null),[pendingImport,setPendingImport]=useState<Casebook|null>(null),[importBusy,setImportBusy]=useState(false),[overwrite,setOverwrite]=useState(false);
 const draft=ctx.folderDrafts.get(folder?.id||''),name=draft?.name??folder?.name??'',notes=draft?.notes??folder?.notes??'',questions=draft?.questions??folder?.questions??'';
 const setDraft=(patch:Partial<FolderDraft>)=>{if(!folder)return;const next={name,notes,questions,...patch};ctx.setFolderDraft(folder.id,next.name===folder.name&&next.notes===folder.notes&&next.questions===folder.questions?null:next);};
 useEffect(()=>{setConfirmDelete(false);setProblem('');},[folder?.id]);
 function action(fn:()=>void){try{fn();setProblem('');}catch(e){setProblem(errorMessage(e));}}
 function remove(entry?:CaseEvidence){if(!folder)return;const before=ctx.book,next={...before,folders:entry?before.folders.map(f=>f.id===folder.id?{...f,updatedAt:new Date().toISOString(),entries:f.entries.filter(e=>e.id!==entry.id)}:f):before.folders.filter(f=>f.id!==folder.id)};action(()=>{const dirty=entry?ctx.entryDrafts.has(JSON.stringify([folder.id,entry.id])):ctx.folderDrafts.has(folder.id)||folder.entries.some(e=>ctx.entryDrafts.has(JSON.stringify([folder.id,e.id])));if(dirty)throw Error('此內容有未儲存的草稿，請先儲存或捨棄草稿，再移除。');ctx.commit(next);setUndo({before,after:JSON.stringify(next),label:entry?'移除引用':'移除案件'});ctx.notify(entry?'引用已移除，可按復原。':'案件已移除，可按復原。');setConfirmDelete(false);if(!entry)ctx.select(next.folders[0]?.id||'');});}
 async function readImport(selected:File|undefined){if(!selected)return;setProblem('');setPendingImport(null);setOverwrite(false);if(selected.size>CASEBOOK_MAX_BYTES){setProblem('案件檔案超過 4 MB，未匯入。');return;}setImportBusy(true);try{const next=await importCasebook(await selected.text());setPendingImport(next);}catch(e){setProblem(errorMessage(e));}finally{setImportBusy(false);if(file.current)file.current.value='';}}
 function confirmImport(replace:boolean){if(!pendingImport)return;action(()=>{if(replace&&(ctx.folderDrafts.size||ctx.entryDrafts.size))throw Error('有未儲存的草稿，請先儲存或捨棄草稿，再取代全部案件。');const before=ctx.book,result=replace?{book:pendingImport,added:pendingImport.folders.length,duplicates:0,renamed:0}:mergeCasebooks(before,pendingImport);ctx.commit(result.book);setUndo({before,after:JSON.stringify(result.book),label:'匯入'});ctx.select(result.book.folders[0]?.id||'');ctx.notify(`匯入完成：新增 ${result.added} 個案件、略過 ${result.duplicates} 個完全相同案件、保留 ${result.renamed} 個衝突副本。`);setPendingImport(null);setOverwrite(false);});}
 return <section className="casebook-panel" aria-label="案件引用資料夾"><header><span className="eyebrow">本機案件資料夾</span><h2>把依據保存成案件資料</h2><p className="casebook-help">案件僅儲存在這個瀏覽器。引用會保留當時的文字與版本，更新後不自動替換。JSON 備份包含引用快照；原始 PDF、表單檔案需另外下載。</p></header>
  {(ctx.error||problem)&&<p className="casebook-error" role="alert">{problem||ctx.error}</p>}{ctx.notice&&<p className="casebook-notice" role="status">{ctx.notice}</p>}{!ctx.ready&&!ctx.error&&<p role="status">正在讀取案件…</p>}{(ctx.folderDrafts.size>0||ctx.entryDrafts.size>0)&&<p className="casebook-draft-notice" role="status">有尚未儲存的筆記。切換案件或關閉面板會暫留草稿；重新整理、關閉網頁前請先儲存。匯出只包含已儲存的內容。</p>}
  <div className="casebook-toolbar"><button type="button" disabled={!ctx.ready} onClick={()=>downloadCaseFile('Openlawtw-案件備份.json',exportCasebookJSON(ctx.book),'application/json')}><Download size={15}/>備份全部案件</button><button type="button" disabled={!ctx.ready||importBusy} onClick={()=>file.current?.click()}><Upload size={15}/>{importBusy?'驗證檔案中…':'匯入 JSON'}</button><input type="file" ref={file} hidden accept=".json,application/json" onChange={e=>void readImport(e.target.files?.[0])}/></div>
  {undo&&<div className="casebook-undo"><span>{undo.label}已完成。</span><button type="button" disabled={JSON.stringify(ctx.book)!==undo.after||ctx.folderDrafts.size>0||ctx.entryDrafts.size>0} onClick={()=>action(()=>{if(JSON.stringify(ctx.book)!==undo.after||ctx.folderDrafts.size||ctx.entryDrafts.size)throw Error('案件已有後續變更或未儲存草稿，請先儲存並匯出目前內容再整理。');ctx.commit(undo.before);ctx.select(undo.before.folders[0]?.id||'');setUndo(null);ctx.notify('已復原。');})}><Undo2 size={14}/>復原上次操作</button>{(JSON.stringify(ctx.book)!==undo.after||ctx.folderDrafts.size>0||ctx.entryDrafts.size>0)&&<small>已有後續變更或未儲存草稿，避免覆蓋新資料，復原已停用。</small>}</div>}
  {pendingImport&&<div className="casebook-import-review"><h3>確認匯入內容</h3><p>{pendingImport.folders.length} 個案件，{pendingImport.folders.reduce((n,f)=>n+f.entries.length,0)} 筆引用。格式與文字雜湊已驗證；仍需自行核對官方來源。</p><p>合併會略過完全相同的案件；識別碼或名稱衝突時保留匯入副本，不覆蓋既有筆記。</p><div className="casebook-button-row"><button type="button" className="casebook-primary" onClick={()=>confirmImport(false)}>合併並保留既有案件</button><button type="button" onClick={()=>setPendingImport(null)}>取消</button></div><label className="casebook-replace"><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/>我已備份，改以此檔取代所有案件</label>{overwrite&&<button type="button" className="casebook-danger" onClick={()=>confirmImport(true)}>確認取代所有案件</button>}</div>}
  <form className="casebook-create" onSubmit={e=>{e.preventDefault();action(()=>{const result=createCaseFolder(ctx.book,newName);ctx.commit(result.book);ctx.select(result.folder.id);setNewName('');ctx.notify('案件已建立，可從條文、函釋、文件或資料包加入引用。');});}}><label>建立案件<input value={newName} onChange={e=>setNewName(e.target.value)} maxLength={120} placeholder="例如：新北店面室內裝修" disabled={!ctx.ready}/></label><button type="submit" disabled={!ctx.ready||!newName.trim()}><FolderPlus size={16}/>建立</button></form>
  {!folder?<p className="casebook-empty">建立案件後，在條文、函釋或文件按「加入案件」，即可保存引用。</p>:<><label className="casebook-folder-select">目前案件<select value={folder.id} onChange={e=>ctx.select(e.target.value)}>{ctx.book.folders.map(f=><option key={f.id} value={f.id}>{f.name}（{f.entries.length} 筆）</option>)}</select></label><div className="casebook-folder-edit"><label>案件名稱<input value={name} maxLength={120} onChange={e=>setDraft({name:e.target.value})}/></label><label>案件筆記<textarea value={notes} maxLength={CASEBOOK_LIMITS.note} rows={3} onChange={e=>setDraft({notes:e.target.value})} placeholder="案址、用途與已知條件；這些筆記不會傳送到伺服器"/></label><label>待確認事項<textarea value={questions} maxLength={CASEBOOK_LIMITS.note} rows={3} onChange={e=>setDraft({questions:e.target.value})} placeholder="例如：是否需變更使用、應洽哪個審查單位"/></label><button type="button" className="casebook-primary" disabled={name===folder.name&&notes===folder.notes&&questions===folder.questions} onClick={()=>action(()=>{ctx.commit(updateCaseFolder(ctx.book,folder.id,{name,notes,questions}));ctx.setFolderDraft(folder.id,null);ctx.notify('案件名稱、筆記與待確認事項已儲存。');})}><Check size={15}/>儲存案件筆記</button></div>
   {draft&&<button type="button" onClick={()=>ctx.setFolderDraft(folder.id,null)}>捨棄案件筆記草稿</button>}<div className="casebook-export-row"><button type="button" onClick={()=>downloadCaseFile(folder.name+'.json',exportCasebookJSON(ctx.book,folder.id),'application/json')}>JSON 備份</button><button type="button" onClick={()=>downloadCaseFile(folder.name+'.md',exportCaseMarkdown(folder),'text/markdown;charset=utf-8')}>Markdown</button><button type="button" onClick={()=>downloadCaseFile(folder.name+'.html',exportCaseHTML(folder),'text/html;charset=utf-8')}>可列印 HTML</button><button type="button" onClick={()=>setConfirmDelete(v=>!v)}><Trash2 size={14}/>移除案件</button></div><p className="casebook-help">匯出使用已儲存的內容。HTML 可用瀏覽器列印為 PDF；案件筆記不會改寫引用原文。</p>
   {confirmDelete&&<div className="casebook-confirm"><p>移除「{folder.name}」與其中 {folder.entries.length} 筆引用？建議先匯出備份，移除後可在本次操作中復原。</p><button type="button" className="casebook-danger" onClick={()=>remove()}>確認移除案件</button><button type="button" onClick={()=>setConfirmDelete(false)}>取消</button></div>}
   <div className="casebook-entry-list">{folder.entries.map(entry=><EvidenceCard key={folder.id+entry.id} entry={entry} folderId={folder.id} onChoose={onChoose} resolveCurrent={resolveCurrent} onRemove={()=>remove(entry)}/>)}{!folder.entries.length&&<p className="casebook-empty">此案件還沒有引用。關閉此面板後，可在閱讀內容旁加入案件。</p>}</div>
  </>}
 </section>;
}
