import {useEffect,useMemo,useState} from 'react';
import {Download,ExternalLink,FileText,Search} from 'lucide-react';
import {loadFile,manifest} from '@/lib/data-client';
import {normalize} from '@/lib/search';
import type {Law} from '@/lib/law-types';
type PdfData={pdf:string;sha256:string;pages:{page:number;text:string}[]};
export function DocumentReader({law,mobile}:{law:Law;mobile:boolean}){
 const [requested,setRequested]=useState(false),[retry,setRetry]=useState(0),[pdf,setPdf]=useState<PdfData|null>(null),[url,setUrl]=useState(''),[error,setError]=useState(false),[query,setQuery]=useState(''),[page,setPage]=useState(1);
 const meta=law.document!;
 useEffect(()=>{if(!requested)return;let live=true;let blob='';setError(false);loadFile<PdfData>(manifest.documents![law.id]).then(async value=>{const bytes=Uint8Array.from(atob(value.pdf),c=>c.charCodeAt(0));if(crypto.subtle){const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(hash!==meta.sha256)throw Error('PDF integrity');}if(!live)return;blob=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));setPdf(value);setUrl(blob);}).catch(()=>{if(live)setError(true);});return()=>{live=false;if(blob)URL.revokeObjectURL(blob);};},[requested,retry,law.id,meta.sha256]);
 const chapters=useMemo(()=>pdf?.pages.filter(p=>p.page>=8&&/^\s*(第[一二三四五六七八九十]+章|附錄)/.test(p.text)).map(p=>({page:p.page,title:p.text.split('\n')[0].trim()}))||[],[pdf]);
 const results=useMemo(()=>query.trim()?pdf?.pages.filter(p=>normalize(p.text).includes(normalize(query)))||[]:[],[pdf,query]);
 return <section className="document-reader"><div className="document-intro"><FileText size={28}/><div><h3>官方圖文 PDF · {meta.pages} 頁</h3><p>保留原始圖表、尺寸及附錄；尚未拆為項款條文。</p></div></div><p className="document-version">{meta.versionNote}</p><div className="document-actions"><a href={meta.sourcePage} target="_blank" rel="noreferrer">核對官方版本<ExternalLink size={14}/></a><a href={meta.source} target="_blank" rel="noreferrer">官方 PDF<ExternalLink size={14}/></a>{!requested&&<button onClick={()=>setRequested(true)}>載入圖文與頁內查找（約 4.3 MB）</button>}{url&&<a href={url} download="建築物無障礙設施設計規範.pdf"><Download size={14}/>下載完整 PDF</a>}</div>
 {requested&&!pdf&&!error&&<p role="status">正在載入圖文原檔…</p>}{error&&<p role="alert">原檔未能載入。<button onClick={()=>setRetry(n=>n+1)}>重試</button>，或使用上方官方 PDF 入口。</p>}
 {pdf&&<><label className="document-search"><Search size={16}/><input aria-label="PDF 頁內查找" placeholder="查找坡道、扶手或 206.2…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{query&&<div className="document-results"><p>{results.length} 頁含有此文字（依 PDF 抽取文字查找）</p>{results.map(p=><button key={p.page} onClick={()=>setPage(p.page)}>PDF 第 {p.page} 頁 · {p.text.replace(/\s+/g,' ').slice(Math.max(0,p.text.replace(/\s+/g,' ').indexOf(query)-20),Math.max(0,p.text.replace(/\s+/g,' ').indexOf(query)-20)+90)}</button>)}</div>}<details className="document-chapters"><summary>章節與附錄</summary><div>{chapters.map(c=><button key={c.page} onClick={()=>setPage(c.page)}>{c.title}<small>PDF {c.page}</small></button>)}</div></details><div className="document-pagebar"><label>PDF 頁碼 <input aria-label="PDF 頁碼" type="number" min={1} max={meta.pages} value={page} onChange={e=>setPage(Math.min(meta.pages,Math.max(1,Number(e.target.value)||1)))}/></label><a href={url+'#page='+page} target="_blank" rel="noreferrer">在獨立視窗開啟第 {page} 頁<ExternalLink size={14}/></a></div>{mobile?<p className="portal-note">手機請由上方開啟或下載 PDF，以便縮放檢視圖面。部分 PDF 閱讀器不支援頁碼跳轉，可在閱讀器輸入 PDF 頁碼。</p>:<iframe key={url+page} title={law.name+' PDF 第 '+page+' 頁'} src={url+'#page='+page+'&view=FitH'} className="document-frame"/>}<p className="portal-note">PDF 頁碼包含封面與目錄，與頁面印製頁碼不同。抽取文字僅供定位，規定與圖表以原檔為準。</p></>}
 </section>;
}
