import {DocumentReader} from '@/components/document-reader';
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,ChevronRight,ChevronDown,ExternalLink,Copy,Bookmark,Link2,Search,X,LoaderCircle,CircleHelp,ArrowUpRight,GitBranch} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RulingCard,ArticleRulings} from '@/components/rulings';
import {ArticleText} from '@/components/article-text';
import {RulingPanel} from '@/components/ruling-panel';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {data,lawById} from '@/lib/catalog';
import {normalize,matchesArticle,searchRulings} from '@/lib/search';
import {lawHref,articleAddress} from '@/lib/routes';
import {shareURL} from '@/lib/portable';
import {useLawRulings} from '@/lib/use-law-rulings';
import type {Article,Law,Ruling} from '@/lib/law-types';
const dateText=(s:string)=>s?s.split('T')[0]:'未提供';
export function Reader({summary,law,loading,error,retry,activeArticle,activeUnit,navigationKey,onChoose,onCopy,open,saved,onSave,mobile,onPairChange,savedRulings,onSaveRuling}:{summary:Law;law:Law|null;loading:boolean;error:boolean;retry:()=>void;activeArticle:string;activeUnit:string;navigationKey:number;onChoose:(id:string,article?:string,unit?:string)=>void;onCopy:(s:string)=>void;open:boolean;saved:boolean;onSave:()=>void;mobile:boolean;onPairChange:(open:boolean)=>void;savedRulings:string[];onSaveRuling:(id:string)=>void}){
  const [fontSize,setFontSize]=useState(18),[requestedFor,setRequestedFor]=useState('');
  const [pair,setPair]=useState<{article:Article|null;initial?:Ruling}|null>(null);
  const trigger=useRef<HTMLElement|null>(null),readingAnchor=useRef<{no:string;offset:number}|null>(null),panelRef=useRef<HTMLElement>(null);
  function capturePosition(){const pane=scroll.current;if(!pane)return;const top=pane.getBoundingClientRect().top;const section=Array.from(pane.querySelectorAll<HTMLElement>('[data-article]')).find(el=>el.getBoundingClientRect().bottom>top);if(section)readingAnchor.current={no:section.dataset.article||'',offset:section.getBoundingClientRect().top-top};}
  function closePair(restoreFocus=true){capturePosition();setPair(null);onPairChange(false);if(restoreFocus)requestAnimationFrame(()=>trigger.current?.focus({preventScroll:true}));}
  function openPair(article:Article|null,initial?:Ruling){setRequestedFor(summary.id);capturePosition();trigger.current=document.activeElement as HTMLElement;setPair({article,initial});onPairChange(true);}
  function openRelated(r:Ruling){openPair(null,r);}
  useLayoutEffect(()=>{const anchor=readingAnchor.current,pane=scroll.current;if(anchor&&pane){const section=Array.from(pane.querySelectorAll<HTMLElement>('[data-article]')).find(el=>el.dataset.article===anchor.no);if(section)pane.scrollTop+=section.getBoundingClientRect().top-pane.getBoundingClientRect().top-anchor.offset;readingAnchor.current=null;}if(pair&&!mobile)panelRef.current?.focus({preventScroll:true});},[!!pair,mobile]);
  useEffect(()=>{setPair(null);onPairChange(false);},[summary.id,activeArticle,activeUnit,navigationKey]);
  useEffect(()=>{if(!open){setPair(null);onPairChange(false);}},[open]);
  const [tab,setTab]=useState('full');const [within,setWithin]=useState('');const scroll=useRef<HTMLDivElement>(null);
  const {counts,countsLoading,countsError,items:rulings,loading:rulingsLoading,error:rulingsError,retry:retryRulings}=useLawRulings(summary.id,open&&requestedFor===summary.id&&(!!pair||tab==='rulings'));
  useEffect(()=>{setTab('full');setWithin('');if(scroll.current)scroll.current.scrollTop=0;},[summary.id,activeArticle,activeUnit,navigationKey]);
  useEffect(()=>{if(!activeArticle||!law||tab!=='full')return;const frame=requestAnimationFrame(()=>{const el=Array.from(scroll.current?.querySelectorAll('[data-article]')||[]).find(e=>articleAddress(e.getAttribute('data-article')||'')===articleAddress(activeArticle));const unit=activeUnit;const target=unit?Array.from(el?.querySelectorAll('[data-unit]')||[]).find(e=>e.getAttribute('data-unit')===unit):el;(target||el)?.scrollIntoView({block:'start',behavior:'instant'});});return ()=>cancelAnimationFrame(frame);},[law,activeArticle,activeUnit,navigationKey,tab]);
  useEffect(()=>{if(scroll.current)scroll.current.scrollTop=0;},[within]);
  const articles=useMemo(()=>(law?.articles||[]).filter(a=>matchesArticle(a,within)),[law,within]);
  const parents=data.relations.filter(r=>r.child===summary.id);
  const children=data.relations.filter(r=>r.parent===summary.id);
  const relatedRulings=useMemo(()=>rulings.filter(r=>r.refs.some(x=>x.law===summary.id)),[rulings,summary.id]);
  const perArticle=useMemo(()=>{const m=new Map<string,Ruling[]>();for(const r of relatedRulings)for(const ref of r.refs)if(ref.law===summary.id&&ref.article){const key=normalize(ref.article);if(!m.get(key)?.some(item=>item.id===r.id))m.set(key,[...(m.get(key)||[]),r]);}return m;},[relatedRulings,summary.id]);
  const [relatedLimit,setRelatedLimit]=useState(30),[relatedQuery,setRelatedQuery]=useState('');
  useEffect(()=>{setRelatedLimit(30);setRelatedQuery('');},[summary.id]);
  const filteredRelated=useMemo(()=>relatedQuery.trim()?searchRulings(relatedRulings,relatedQuery):relatedRulings,[relatedRulings,relatedQuery]);
  const panel=pair?<RulingPanel key={summary.id+':'+(pair.article?.no||'law')+':'+(pair.initial?.id||'')} law={summary} article={pair.article} items={pair.article?perArticle.get(normalize(pair.article.no))||[]:relatedRulings} initial={pair.initial} count={pair.article?counts?.articles[normalize(pair.article.no)]:counts?.total} summariesLoading={rulingsLoading} summariesError={!!rulingsError} onRetry={retryRulings} onClose={()=>closePair()} onChoose={(id,no,unit)=>{closePair();onChoose(id,no,unit);}} onCopy={onCopy} saved={savedRulings} onSave={onSaveRuling}/>:null;
  return <div className={'reader-comparison '+(pair&&!mobile?'is-open':'')}><div className="reader" style={{height:'100%'}}>
    <div className="reader-top"><div className="reader-headingline"><div className="reader-breadcrumb"><BookOpen size={13}/>{summary.region}<ChevronRight size={11}/>{summary.category}</div><div className="law-badges"><span className="badge">{summary.kind}</span><span className={'badge '+(summary.coverage==='full'?'red':'gold')}>{summary.document?'圖文 PDF':summary.coverage==='full'?'全文快照':'官方連結'}</span></div></div><h2>{summary.name}</h2><div className="reader-information"><div className="law-meta"><span>{summary.modified?'修正 '+summary.modified:'修正日期待核對'}</span><span>{(summary.articleCount||0)?(summary.articleCount||0)+' 條原文':summary.document?summary.document.pages+' 頁官方 PDF':'全文待收錄'}</span></div><div className="reader-actions"><a href={summary.url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>官方原文與歷史版本</a><button onClick={()=>onCopy(summary.name+'\n'+summary.url)}><Copy size={13}/>複製引用</button><button className={saved?'is-saved':''} onClick={onSave} aria-pressed={saved}><Bookmark size={14} fill={saved?'currentColor':'none'}/>{saved?'已收藏':'收藏'}</button><button onClick={()=>onCopy(shareURL()+lawHref(summary.id,activeArticle,activeUnit))}><Link2 size={13}/>連結</button></div></div></div>
    {loading&&<div className="loading-line"/>}
    <Tabs value={tab} onValueChange={value=>{if(pair)closePair(false);if(value==='rulings')setRequestedFor(summary.id);setTab(value);}} className="reader-tabroot"><div className="reader-tabbar"><TabsList aria-label="法規內容"><TabsTrigger value="full">{summary.document?'圖文規範':'條文'}</TabsTrigger><TabsTrigger value="rulings">解釋函令 <span className="tab-count">{counts?.total??(countsLoading?'…':'')}</span></TabsTrigger><TabsTrigger value="relations">法源</TabsTrigger><TabsTrigger value="source">版本・附件</TabsTrigger></TabsList>{tab==='full'&&summary.coverage==='full'&&<div className="article-search"><Search size={14}/><input value={within} onChange={e=>{if(pair)closePair(false);setWithin(e.target.value);}} aria-label="在此法規搜尋" placeholder="本法規內搜尋／條號" enterKeyHint="search"/>{within&&<button className="icon-btn" onClick={()=>{if(pair)closePair(false);setWithin('');}} aria-label="清除此法規搜尋"><X size={13}/></button>}<div className="font-controls"><button aria-label="縮小條文字級" disabled={fontSize<=16} onClick={()=>setFontSize(n=>n-2)}>A−</button><button aria-label="放大條文字級" disabled={fontSize>=22} onClick={()=>setFontSize(n=>n+2)}>A+</button></div></div>}</div>
      <TabsContent value="full" className="reader-scroll" ref={scroll}><div className="reading-column">
        {loading?<div className="empty-state"><LoaderCircle size={24}/>正在載入官方條文快照…</div>:error?<div className="empty-state"><CircleHelp size={28}/><strong>全文暫時無法載入</strong><button className="plain-button" onClick={retry}>重試</button><br/><a href={summary.url} target="_blank" rel="noreferrer">開啟官方原文<ExternalLink size={14}/></a></div>:summary.document?<DocumentReader key={summary.id} law={summary} mobile={mobile}/>:summary.coverage==='link'?<div className="empty-state"><Link2 size={28}/><strong>已建立官方連結</strong>這部法規尚未完成全文收錄。<br/>請由官方頁面核對現行條文。<a href={summary.url} target="_blank" rel="noreferrer">前往官方網站<ArrowUpRight size={15}/></a></div>:<>

          {(summary.attachments.length>0||children.length>0)&&<nav className="law-resource-strip" aria-label="本法規資源"><span>本法規資源</span>{summary.attachments.length>0&&<button onClick={()=>setTab('source')}>官方附件 {summary.attachments.length}<ArrowUpRight size={12}/></button>}{children.length>0&&<button onClick={()=>setTab('relations')}>已收錄子法 {children.length}<ArrowUpRight size={12}/></button>}</nav>}
          {law?.effectiveNote&&<div className="status-line">生效說明：{law.effectiveNote}</div>}
          {articles.map((a,i)=><div key={a.no}>{a.path.length&&(i===0||a.path.join('/')!==articles[i-1].path.join('/'))?<div className="chapter-heading">{a.path.join(' / ')}</div>:null}<section id={a.anchor} data-article={a.no} className={'article-section '+(!!activeArticle&&articleAddress(activeArticle)===articleAddress(a.no)?'target':'')+(pair?.article?.no===a.no?' comparing':'')}><div className="article-heading"><h3 className="article-no">{a.no}</h3><ArticleRulings article={a.no} count={counts?.articles[normalize(a.no)]??0} active={pair?.article?.no===a.no} loading={countsLoading} error={countsError} onOpen={()=>countsError?retryRulings():pair?.article?.no===a.no?closePair():openPair(a)}/>{children.some(r=>r.article&&articleAddress(r.article)===articleAddress(a.no))&&<details className="article-resources"><summary>子法 {children.filter(r=>r.article&&articleAddress(r.article)===articleAddress(a.no)).length}</summary><div>{children.filter(r=>r.article&&articleAddress(r.article)===articleAddress(a.no)).map(r=><button className="related-provision-link" key={r.child} onClick={()=>onChoose(r.child)}>{lawById.get(r.child)?.name}<ArrowUpRight size={11}/></button>)}</div></details>}<button className="article-copy" aria-label={'複製'+a.no} onClick={()=>onCopy(summary.name+' '+a.no+'\n'+a.text+'\n'+summary.url)}><Copy size={13}/></button></div><ArticleText article={a} law={summary} query={within} fontSize={fontSize} onCopy={onCopy} onChoose={onChoose} activeUnit={activeUnit}/></section></div>)}
          {!articles.length&&<div className="empty-state">此法規內沒有符合的條文。</div>}
          <div className="coverage-note">條文保留官方文字。圖表、公式與附表請至「版本・附件」開啟原檔。來源快照日期：{summary.snapshot||'來源頁面逐筆擷取'}。</div>
        </>}
      </div></TabsContent>
      <TabsContent value="relations" className="reader-scroll">
        <h3 className="reader-subtitle">{summary.kind==='法律'&&!parents.length?'法規層級':'訂定依據'}</h3>{parents.map(r=><div className="relation-link" key={r.parent}><button onClick={()=>onChoose(r.parent,r.article)}><GitBranch size={16}/>{lawById.get(r.parent)?.name} {r.article}</button><p>{r.evidence}</p><a className="plain-button" style={{fontSize:12}} href={r.source} target="_blank" rel="noreferrer">核對依據原文<ExternalLink size={12}/></a></div>)}{!parents.length&&<p style={{fontSize:13,color:'#8492a3'}}>{summary.kind==='法律'?'本法屬法律層級；法規沿革請見「版本・附件」。':'目前尚未建立可核對的訂定依據，請查閱官方原文。'}</p>}
        {children.length>0&&<><h3 className="reader-subtitle">依本法規訂定的已收錄規定</h3>{children.map(r=><div className="relation-link" key={r.child}><button onClick={()=>onChoose(r.child)}>{lawById.get(r.child)?.name}<ChevronRight size={14}/></button><p>{r.article}</p></div>)}</>}
      </TabsContent>
      <TabsContent value="rulings" className="reader-scroll"><div className="law-rulings-head"><div><h3>這部法規的解釋函令 <span>{counts?.total??relatedRulings.length}</span></h3><p>依原文明示名稱與條號連結；收錄不代表現時有效。</p></div><label className="ruling-search"><Search size={15}/><input aria-label="搜尋本法規相關函釋" placeholder="搜尋相關函釋，或輸入條號" value={relatedQuery} onChange={e=>{setRelatedQuery(e.target.value);setRelatedLimit(30);}}/>{relatedQuery&&<button aria-label="清除相關函釋搜尋" onClick={()=>setRelatedQuery('')}><X size={14}/></button>}</label></div>
      {rulingsError?<div className="coverage-note" role="alert">相關函釋摘要尚未下載，請連線後重試。<button className="plain-button" onClick={retryRulings}>重新載入函釋</button></div>:rulingsLoading?<p>正在載入函釋…</p>:<><div className="ruling-result-count">{filteredRelated.length} 筆</div>{filteredRelated.slice(0,relatedLimit).map(r=><RulingCard key={r.id} ruling={r} onClick={()=>openRelated(r)}/>)}{filteredRelated.length>relatedLimit&&<button className="load-more" onClick={()=>setRelatedLimit(n=>n+30)}>更多函釋<ChevronDown size={15}/></button>}{!filteredRelated.length&&<div className="empty-state">目前沒有相符的已收錄函釋。</div>}</>}
      </TabsContent>
      <TabsContent value="source" className="reader-scroll">
        <h3 className="reader-subtitle">資料來源與版本</h3><dl className="info-grid"><dt>來源</dt><dd>{summary.source}</dd><dt>法規代碼</dt><dd>{summary.id}</dd><dt>修正日期</dt><dd>{summary.modified||'待核對'}</dd><dt>生效日期</dt><dd>{summary.effective?.startsWith('9999')?'請依官方生效說明':summary.effective||'未另列；請查條文與沿革'}</dd><dt>批次日期</dt><dd>{summary.snapshot||'逐筆擷取來源頁面'}</dd><dt>擷取日期</dt><dd>{summary.retrieved?dateText(summary.retrieved):'連結待核對'}</dd></dl>
        <div className="coverage-note">本版為固定資料快照。修正、公布與生效日期不一定相同；歷史版本由官方原文入口查閱。</div>
        {law?.version&&<dl className="info-grid"><dt>本庫觀測此版本</dt><dd>{dateText(law.version.observedAt)}</dd><dt>內容版本</dt><dd><code>{law.contentHash?.slice(0,16)}</code></dd><dt>前次觀測</dt><dd>{law.version.previousContentHash?'已有異動紀錄':'本庫初始基準，未追溯歷史'}</dd></dl>}<h3 className="reader-subtitle">官方附件 · {summary.attachments.length}</h3><div className="link-list">{summary.attachments.map(a=><a href={a.url} key={a.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/>{a.title}</a>)}</div>{!summary.attachments.length&&<p style={{fontSize:13,color:'#8795a6'}}>目前資料未列附件。</p>}
        {law?.history&&<><h3 className="reader-subtitle">法規沿革</h3><div className="history">{law.history}</div></>}
      </TabsContent>
    </Tabs>
  </div>{pair&&!mobile&&<aside className="ruling-side-panel" ref={panelRef} tabIndex={-1} aria-label="條文旁函釋閱讀區" onKeyDown={e=>{if(e.key==='Escape')closePair();}}>{panel}</aside>}
  <Sheet open={!!pair&&mobile} onOpenChange={v=>{if(!v)closePair();}}><SheetContent side="bottom" className="ruling-bottom-sheet" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();trigger.current?.focus({preventScroll:true});}}><SheetTitle className="sr-only">{pair?.article?.no||'本法規'}解釋令</SheetTitle><SheetDescription className="sr-only">閱讀相關函釋，關閉後回到原條文。</SheetDescription>{mobile&&panel}</SheetContent></Sheet>
  </div>;
}
