import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Search,MapPin,BookOpen,FileText,ChevronDown} from 'lucide-react';
import {data} from '@/lib/catalog';
import {regionCoverage} from '@/lib/coverage';
import {lawHref} from '@/lib/routes';
export function LawPortal({region,onRegion,onSearch,onChoose,onCoverage}:{region:string;onRegion:(region:string)=>void;onSearch:(q:string)=>void;onChoose:(id:string)=>void;onCoverage:()=>void}){
 const [q,setQ]=useState('');const pane=useRef<HTMLDivElement>(null);useEffect(()=>{if(pane.current)pane.current.scrollTop=0;},[region]);
 const local=region!=='全台';
 const coverage=useMemo(()=>regionCoverage(data.laws,region),[region]);
 const totalFull=data.laws.filter(l=>l.coverage==='full').length;
 const selectedRegion=data.regions.find(r=>r.name===region);
 const featured=(local?coverage.full:data.laws.filter(l=>['D0070109','D0070115','D0070116','D0070117','內政部-GL000734'].includes(l.id))).slice(0,6);
 const sources=data.resources.filter(r=>r.region===region||r.region==='中央').slice(0,5);
 return <div ref={pane} className="law-portal" aria-label="法規搜尋首頁">
  <section className="portal-hero">
   <div className="portal-intro"><div className="portal-kicker"><span/>OPEN LAW · TAIWAN</div><h1>{local?<>{region}的建築法規，<br/><em>在這裡接著查。</em></>:<>讓法規，<br/><em>回到設計的手邊。</em></>}</h1><p>從中央條文到地方規定，連同相關函釋，<br className="desktop-break"/>整理成一本可以隨手查閱的建築法規庫。</p>
    <form className="portal-search" role="search" onSubmit={e=>{e.preventDefault();if(q.trim())onSearch(q.trim());}}><Search size={21}/><input value={q} onChange={e=>setQ(e.target.value)} aria-label="首頁搜尋法規" placeholder="試試「變更使用」或「建技90」" enterKeyHint="search" required/><button aria-label="查找法規" type="submit"><ArrowRight size={21}/></button></form>
    <div className="portal-search-tools"><label><MapPin size={14}/><select aria-label="首頁選擇縣市" value={region} onChange={e=>onRegion(e.target.value)}><option value="全台">全台縣市</option>{data.regions.map(r=><option key={r.name}>{r.name}</option>)}</select><ChevronDown size={12}/></label><span>熱門查找</span>{['變更使用','畸零地','室內裝修'].map(t=><button key={t} onClick={()=>onSearch(t)}>{t}</button>)}</div>
   </div>
   <div className="portal-art" aria-hidden="true"><div className="art-orbit"/><span className="art-edition">A PUBLIC REFERENCE / 01</span><div className="paper-sheet sheet-back"><span>地方自治</span><i/><i/><i/></div><div className="paper-sheet sheet-mid"><span>中央法規</span><i/><i/><i/></div><div className="paper-sheet sheet-front"><span>建築法</span><strong>§</strong><div className="paper-rule"/><small>條文・函釋・地方規定</small></div><div className="art-caption"><span>以原文為起點</span><span>連結每一份依據 ↗</span></div></div>
  </section>
  <div className="portal-stats"><div><strong>{data.laws.length.toLocaleString()}</strong><span>部法規索引</span></div><div><strong>{totalFull.toLocaleString()}</strong><span>部已收錄全文</span></div><div><strong>{data.rulingStats.count.toLocaleString()}</strong><span>筆函釋</span></div><button onClick={onCoverage}>查看收錄範圍與缺口<ArrowUpRight size={15}/></button></div>
  {local?<section className="portal-region-content"><div className="portal-section-title"><div><span>LOCAL REFERENCE</span><h2>{region}法規指南</h2></div><button onClick={()=>onRegion('全台')}>查看全部縣市<ArrowUpRight size={15}/></button></div><p className="portal-note">本地已收錄 {coverage.full.length} 部全文、{coverage.links.length} 筆官方連結。搜尋亦包含中央法規；以下依名稱分類，不代表全部適用規定。</p><div className="portal-topics">{coverage.topics.map(t=><details key={t.id}><summary><span>{t.name}</span><small>{t.laws.length?`${t.laws.length} 部已索引`:'待補收錄'}</small><ChevronDown size={15}/></summary><div>{t.laws.length?t.laws.map(l=><a key={l.id} href={lawHref(l.id)} onClick={e=>{e.preventDefault();onChoose(l.id);}}>{l.name}<small>{l.coverage==='full'?'全文':'官方連結'} ↗</small></a>):<p>目前尚無對應索引，可由官方入口查閱。</p>}</div></details>)}</div><div className="portal-source-row">{selectedRegion&&<a href={selectedRegion.url} target="_blank" rel="noreferrer">{region}官方法規入口<ArrowUpRight size={15}/></a>}<button onClick={onCoverage}>檢查資料收錄情形<ArrowUpRight size={15}/></button></div></section>:<section className="portal-regions"><div className="portal-section-title"><div><span>FIND YOUR PLACE</span><h2>從你的縣市開始</h2></div><p>選擇地區，集中查找地方規定。</p></div><div className="region-grid">{data.regions.map((r,i)=>{const full=data.laws.filter(l=>l.region===r.name&&l.coverage==='full').length;return <button key={r.name} onClick={()=>onRegion(r.name)}><span className="region-order">{String(i+1).padStart(2,'0')}</span><strong>{r.name}</strong><small>{full?`${full} 部全文`:'全文待補'}</small><ArrowUpRight size={15}/></button>;})}</div></section>}
  <section className="portal-reference-grid"><div><div className="portal-section-title"><div><span>ON YOUR DESK</span><h2>{local?'本地法規':'常用中央法規'}</h2></div><BookOpen size={21}/></div><div className="portal-law-list">{featured.map(l=><a key={l.id} href={lawHref(l.id)} onClick={e=>{e.preventDefault();onChoose(l.id);}}><span>{l.name}<small>{l.kind} · {l.document?`${l.document.pages} 頁圖文 PDF`:`${l.articleCount||0} 條／點原文`}</small></span><ArrowUpRight size={17}/></a>)}{!featured.length&&<p className="portal-note">本地全文尚待補齊，請先查閱官方來源。</p>}</div></div><div className="portal-editorial"><FileText size={23}/><h2>查得到，也看得見依據。</h2><p>條文旁開啟函釋，保留閱讀位置。每份資料提供官方來源，方便回到原文核對。</p>{sources.length>0&&<div className="portal-resource-links">{sources.map(r=><a key={r.url+r.title} href={r.url} target="_blank" rel="noreferrer">{r.title}<ArrowUpRight size={14}/></a>)}</div>}<button onClick={onCoverage}>了解資料與開源<ArrowRight size={16}/></button></div></section>
  <footer className="portal-footer"><span>openlawtw <small>臺灣建築法規庫</small></span><p>尚未完整收錄全台規定。查無結果不代表沒有規定；適用範圍與現行效力請核對官方來源。</p><small>v{data.version} · 程式碼 MIT</small></footer>
 </div>;
}
