import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowUpRight,BookOpen,ChevronRight,Download,Focus,Layers3,Maximize2,Minus,Network,Pause,Play,Plus,Search,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {data,lawById} from '@/lib/catalog';
import {loadFile,loadRuling,manifest} from '@/lib/data-client';
import {normalize} from '@/lib/search';
import {buildUniverse,lawFamily,scopedUniverse,universeFocus,type UniverseLawData,type UniverseRulingData,type UniverseRuling} from '@/lib/universe';
import type {Ruling} from '@/lib/law-types';
import {UniverseCanvas,type UniverseCanvasHandle} from './universe-canvas';

const count=(n:number)=>n.toLocaleString('zh-TW');
const tourLaws=['D0070109','D0070001','D0070249','D0070115'];
export function LawUniverse({open,onClose,onChoose,onRuling}:{open:boolean;onClose:()=>void;onChoose:(id:string,article?:string)=>void;onRuling:(r:Ruling)=>void}){
 const [layout,setLayout]=useState<UniverseLawData|null>(null),[rulings,setRulings]=useState<UniverseRuling[]>([]),[rulingReady,setRulingReady]=useState(false),[showRulings,setShowRulings]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const [selected,setSelected]=useState(''),[region,setRegion]=useState('全台'),[query,setQuery]=useState(''),[searchLimit,setSearchLimit]=useState(30),[zoom,setZoom]=useState(100),[tour,setTour]=useState(false),[present,setPresent]=useState(false),[details,setDetails]=useState(false),[listLimit,setListLimit]=useState(30),[opening,setOpening]=useState(false),[openError,setOpenError]=useState('');
 const canvas=useRef<UniverseCanvasHandle>(null),queryInput=useRef<HTMLInputElement>(null),tourIndex=useRef(0),session=useRef(0);
 useEffect(()=>{session.current++;if(!open){setTour(false);setPresent(false);setOpening(false);setOpenError('');}},[open]);
 useEffect(()=>{if(!open)return;const controller=new AbortController();setError('');setLoading(true);(async()=>{if(!layout){if(!manifest.universe)throw Error('本版尚未提供關係圖資料');setLayout(await loadFile<UniverseLawData>(manifest.universe,controller.signal));}if(showRulings&&!rulingReady){if(!manifest.universeRulings)throw Error('本版尚未提供函釋關係資料');const d=await loadFile<UniverseRulingData>(manifest.universeRulings,controller.signal);setRulings(d.items);setRulingReady(true);}})().catch(e=>{if(e.name!=='AbortError')setError('關係資料尚未下載，請連線後重試。');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[open,showRulings,retry]);
 const graph=useMemo(()=>buildUniverse(data.laws,data.relations,layout?.points??[],showRulings?rulings:[]),[layout,showRulings,rulings]);
 const scoped=useMemo(()=>scopedUniverse(graph,region),[graph,region]);
 const focus=useMemo(()=>selected?universeFocus(selected,scoped,data.relations):null,[selected,scoped]);
 const node=scoped.byId.get(selected),law=node?.kind==='law'?lawById.get(node.sourceId):undefined,ruling=node?.kind==='ruling'?rulings.find(r=>r.id===node.sourceId):undefined;
 const family=useMemo(()=>law?lawFamily(law.id,data.relations):null,[law]);
 const children=family?[...family.descendants].map(id=>lawById.get(id)!).filter(l=>l&&scoped.byId.has('l:'+l.id)):[];
 const nearby=scoped.edges.filter(e=>e.from===selected||e.to===selected);
 const visibleLaws=scoped.nodes.filter(n=>n.kind==='law'),visibleRulings=scoped.nodes.length-visibleLaws.length,basisCount=scoped.edges.filter(e=>e.kind==='basis').length,citationCount=scoped.edges.filter(e=>e.kind==='citation').length;
 const results=useMemo(()=>{const q=normalize(query);return q?scoped.nodes.filter(n=>normalize(n.label).includes(q)||(n.kind==='law'&&normalize(lawById.get(n.sourceId)?.keywords.join(' ')??'').includes(q))):[];},[query,scoped]);
 const stop=()=>setTour(false);
 function cancelOpening(){session.current++;setOpening(false);setOpenError('');}
 function select(id:string){stop();cancelOpening();setSelected(id);setDetails(true);setQuery('');setListLimit(30);}
 function overview(){stop();cancelOpening();setSelected('');setDetails(false);setQuery('');canvas.current?.fit();}
 function scope(value:string){stop();cancelOpening();setRegion(value);setSelected('');setDetails(false);}
 useEffect(()=>{if(!tour||!open)return;const mq=window.matchMedia('(prefers-reduced-motion: reduce)');if(mq.matches){setTour(false);return;}const next=()=>{if(document.hidden)return;const id='l:'+tourLaws[tourIndex.current++%tourLaws.length];if(!scoped.byId.has(id))return;setSelected(id);setDetails(true);canvas.current?.fit(universeFocus(id,scoped,data.relations),true);};next();const timer=setInterval(next,5000);const hidden=()=>{if(document.hidden)setTour(false);},reduced=()=>setTour(false);document.addEventListener('visibilitychange',hidden);mq.addEventListener('change',reduced);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',hidden);mq.removeEventListener('change',reduced);};},[tour,open,scoped]);
 async function readRuling(){if(!ruling)return;const token=++session.current;setOpening(true);setOpenError('');try{const full=await loadRuling(ruling.id);if(session.current===token)onRuling(full);}catch{if(session.current===token)setOpenError('全文尚未下載，請連線重試，或開啟官方原文。');}finally{if(session.current===token)setOpening(false);}}
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent fullScreen className={'universe-dialog '+(present?'universe-present':'')} showCloseButton={false} onOpenAutoFocus={e=>{e.preventDefault();queryInput.current?.focus();}}>
 <header className="universe-header"><div className="universe-brand"><span className="universe-mark"><Network size={23} strokeWidth={1.3}/></span><div><span className="universe-eyebrow">OPENLAWTW / LEGAL ATLAS</span><DialogTitle>法規宇宙</DialogTitle></div></div><DialogDescription className="universe-description">沿著法源與引用，讀懂法規之間的關係。</DialogDescription><div className="universe-header-actions"><button onClick={()=>{setPresent(v=>!v);stop();}} aria-pressed={present}><Maximize2 size={16}/><span>{present?'顯示面板':'純圖模式'}</span></button><button onClick={onClose} className="universe-back"><ArrowLeft size={16}/><span>返回閱讀</span></button></div></header>
 <div className="universe-toolbar"><div className="universe-search"><Search size={17}/><input ref={queryInput} aria-label="搜尋宇宙圖節點" placeholder="找一部法規，展開它的關係" value={query} onFocus={stop} onChange={e=>{setQuery(e.target.value);setSearchLimit(30);}} onKeyDown={e=>{if(e.key==='Enter'&&results.length){e.preventDefault();select(results[0].id);canvas.current?.fit(universeFocus(results[0].id,scoped,data.relations));}}}/>{query&&<button aria-label="清除節點搜尋" onClick={()=>setQuery('')}><X size={15}/></button>}{query&&<div className="universe-search-results" role="region" aria-label="節點搜尋結果"><div className="universe-result-count">{count(results.length)} 個節點</div>{results.slice(0,searchLimit).map(n=><button key={n.id} onClick={()=>{select(n.id);canvas.current?.fit(universeFocus(n.id,scoped,data.relations));}}><span>{n.label}</span><small>{n.kind==='law'?n.region:'函釋'}</small></button>)}{!results.length&&<p>目前圖層找不到此名稱，試試「建築法」。</p>}{results.length>searchLimit&&<button onClick={()=>setSearchLimit(n=>n+50)}>顯示更多結果</button>}</div>}</div>
 <label className="universe-region"><span>範圍</span><select value={region} onChange={e=>scope(e.target.value)} aria-label="宇宙圖縣市範圍"><option>全台</option><option value="中央">中央</option>{data.regions.map(r=><option key={r.name}>{r.name}</option>)}</select></label>
 <label className="universe-layer"><input type="checkbox" checked={showRulings} onChange={e=>{stop();cancelOpening();setShowRulings(e.target.checked);if(selected.startsWith('r:'))setSelected('');}}/><Layers3 size={16}/><span>函釋與互引</span></label>
 <button className="universe-tour" onClick={()=>{if(!tour){setQuery('');setRegion('全台');}setTour(v=>!v);}} aria-pressed={tour}>{tour?<Pause size={15}/>:<Play size={15}/>}<span>{tour?'暫停導覽':'播放導覽'}</span></button><button className="universe-export" onClick={()=>canvas.current?.exportPNG()} disabled={!layout}><Download size={16}/><span>匯出圖像</span></button></div>
 <div className="universe-body"><div className="universe-stage"><div className="universe-map-caption"><span className="universe-eyebrow">THE CONNECTED LAW LIBRARY</span><h2>{selected?'循著一部法規，展開關係。':'一部法規，從來不是一座孤島。'}</h2><p>{count(visibleLaws.length)} 部法規<span>／</span>{count(basisCount)} 筆法源關係{showRulings&&<> <span>／</span>{count(visibleRulings)} 筆函釋</>}</p></div>
 {layout?<UniverseCanvas ref={canvas} graph={scoped} focus={focus} selected={selected} onSelect={select} onInteract={stop} onZoom={setZoom}/>:<div className="universe-map-loading">{error||'正在展開法規關係…'}</div>}
 {(loading||error)&&<div className="universe-load-status" role={error?'alert':'status'}>{error||'正在載入關係資料…'}{error&&<button onClick={()=>setRetry(n=>n+1)}>重新載入</button>}</div>}
 <div className="universe-legend"><span><i className="legend-law"/>中央法規</span><span><i className="legend-local"/>地方法規</span>{showRulings&&<span><i className="legend-ruling"/>函釋</span>}<span><b/>法源關係</span>{showRulings&&<span><b className="legend-dash"/>函釋互引 {count(citationCount)}</span>}</div>
 <div className="universe-map-controls"><button aria-label="放大宇宙圖" onClick={()=>{stop();canvas.current?.zoom(1.25);}}><Plus size={18}/></button><span aria-live="off">{zoom}%</span><button aria-label="縮小宇宙圖" onClick={()=>{stop();canvas.current?.zoom(.8);}}><Minus size={18}/></button><button aria-label="顯示全圖" title="顯示全圖" onClick={overview}><Maximize2 size={17}/></button>{selected&&<button aria-label="聚焦選取節點的關係" title="聚焦關係" onClick={()=>{stop();canvas.current?.fit(focus??undefined,true);}}><Focus size={17}/></button>}</div>
 <p className="universe-map-hint">拖曳平移 · 滾輪或雙指縮放 · 點選節點</p>
 {node&&<button className="universe-mobile-selection" onClick={()=>setDetails(v=>!v)}>{node.label}<ChevronRight size={15}/></button>}
 </div>
 <aside className={'universe-inspector '+(details?'is-visible':'')} aria-label="宇宙圖節點與關係"><button className="universe-mobile-close" onClick={()=>setDetails(false)} aria-label="收合節點詳情"><X size={18}/></button>
 {node?<><div className="universe-inspector-kicker">{law?law.region+' / '+law.kind:'官方函釋'}</div><h2>{law?.name||ruling?.title||node.label}</h2>{ruling&&<p className="universe-node-meta">{ruling.number||'字號待核對'}<br/>{ruling.date?'發文 '+ruling.date:'發文日期待核對'}</p>}
 <div className="universe-node-actions"><button className="universe-primary" disabled={opening} onClick={()=>law?onChoose(law.id):readRuling()}><BookOpen size={16}/>{opening?'正在開啟…':law?'閱讀法規':'閱讀函釋'}</button><button onClick={()=>{stop();canvas.current?.fit(focus??undefined,true);}}><Focus size={16}/>聚焦</button></div>{openError&&<p role="alert">{openError}</p>}
 <a className="universe-source" href={law?.url||ruling?.url} target="_blank" rel="noreferrer">官方原文<ArrowUpRight size={14}/></a>
 {law&&<><div className="universe-node-stats"><div><strong>{count(children.length)}</strong><span>下游法規</span></div><div><strong>{count(children.filter(l=>l.region!=='中央').length)}</strong><span>其中地方法規</span></div></div><p className="universe-method">沿已收錄法源關係逐層展開，包含直接與間接連結；未連線不代表無關。</p></>}
 <h3>直接關係 <span>{nearby.length}</span></h3>{!nearby.length&&<p className="universe-empty">此節點尚未建立連線。可直接閱讀原文，或開啟函釋圖層。</p>}
 <div className="universe-relations">{nearby.slice(0,listLimit).map((e,i)=>{const other=scoped.byId.get(e.from===selected?e.to:e.from)!;return <div className="universe-relation" key={e.from+e.to+e.kind+i}><small>{e.kind==='basis'?(e.from===selected?'訂定依據所連結的法規':'本法規的訂定依據'):e.kind==='citation'?(e.from===selected?'本函引用':'引用本函'):'函釋明示引法'}</small><button onClick={()=>select(other.id)}>{other.label}<ChevronRight size={13}/></button>{e.evidence&&<details><summary>查看原文依據 · {e.evidence.article}</summary><p>{e.evidence.evidence}</p><a href={e.evidence.source} target="_blank" rel="noreferrer">核對官方來源<ArrowUpRight size={12}/></a><button onClick={()=>onChoose(e.evidence!.parent,e.evidence!.article)}>閱讀依據條文</button></details>}</div>;})}</div>{nearby.length>listLimit&&<button className="universe-more" onClick={()=>setListLimit(n=>n+40)}>展開更多關係（尚有 {nearby.length-listLimit} 筆）</button>}
 <button className="universe-reset" onClick={overview}><ArrowLeft size={14}/>回到全圖</button></>:<><div className="universe-inspector-kicker">從一個節點開始</div><h2>法律的脈絡，<br/>在連線之間。</h2><p className="universe-intro">選一部常用法規，看見它的訂定依據、下游法規，以及各縣市已建立的連結。</p><div className="universe-shortcuts">{tourLaws.map(id=>{const l=lawById.get(id);return l?<button key={id} onClick={()=>{select('l:'+id);canvas.current?.fit(universeFocus('l:'+id,scoped,data.relations),true);}}><span>{l.name}</span><ArrowUpRight size={15}/></button>:null;})}</div><div className="universe-reading-key"><h3>怎麼閱讀這張圖</h3><p>每個節點是一部法規。圓點越大，代表已收錄的法源連線越多。</p><p>箭頭由訂定依據指向引用該依據的法規；函釋圖層另外呈現引法與互引。</p><p>位置與距離僅為排版，不代表法規位階、適用性或重要程度。</p></div><p className="universe-snapshot">資料批次 {data.snapshot}<br/>收錄範圍有限，請核對官方原文。</p></>}
 </aside></div><footer className="universe-footer"><span>中央與地方，同一張圖。</span><span>連線有據 · 不作適用判定</span><span>openlawtw</span></footer>
 </DialogContent></Dialog>;
}
