import {useEffect,useState} from 'react';
import {Download,Check,RefreshCw,Trash2} from 'lucide-react';
import {manifest} from '@/lib/data-client';
const size=(n:number)=>(n/1024/1024).toFixed(1)+' MB';
export function OfflinePacks({region,ready,online}:{region:string;ready:boolean;online:boolean}){
 const [states,setStates]=useState<{id:string;selected:boolean;complete:boolean}[]>([]),[busy,setBusy]=useState(''),[progress,setProgress]=useState(0),[message,setMessage]=useState(''),[all,setAll]=useState(false);
 useEffect(()=>{const listener=(event:MessageEvent)=>{const d=event.data;if(d?.type==='PACK_STATUS')setStates(d.packs);if(d?.type==='PACK_PROGRESS'){setBusy(d.packId);setProgress(d.total?d.done/d.total:0);}if(d?.type==='PACK_READY'){setBusy('');setMessage('離線資料已更新。');}if(d?.type==='PACK_FAILED'){setBusy('');setMessage(d.message);}};navigator.serviceWorker.addEventListener('message',listener);navigator.serviceWorker.controller?.postMessage({type:'STATUS'});return()=>navigator.serviceWorker.removeEventListener('message',listener);},[ready]);
 function send(type:string,id:string){setMessage('');setBusy(id);setProgress(0);const controller=navigator.serviceWorker.controller;if(!controller){setBusy('');setMessage('網站介面仍在準備中，完成後請重試。');return;}controller.postMessage({type,packId:id});}
 const shown=manifest.packs.filter(p=>all||p.id==='中央'||p.id===region||p.id==='rulings'||states.some(s=>s.id===p.id&&s.selected));
 return <section className="offline-packs"><div className="pwa-divider"/><h3>選擇離線資料</h3><p>建議先下載中央法規與工作縣市。函釋全文可另外下載；更新時只補上有異動的分片。</p><div className="offline-pack-list">{shown.map(p=>{const state=states.find(s=>s.id===p.id),downloading=busy===p.id;return <div className="offline-pack" key={p.id}><div><strong>{p.label}</strong><small>{p.lawCount.toLocaleString()} {p.id==='rulings'?'筆函釋':'部法規'} · {size(p.bytes)}</small>{state?.selected&&!state.complete&&<small className="pack-warning">資料不完整，請重新下載</small>}{downloading&&<progress aria-label={p.label+'下載進度'} value={progress} max={1}/>}</div><button className={state?.complete?'pack-ready':''} disabled={!ready||!online||!!busy||!p.lawCount} onClick={()=>send('PACK_DOWNLOAD',p.id)} aria-label={'下載'+p.label}>{downloading?<RefreshCw size={15}/>:state?.complete?<Check size={15}/>:<Download size={15}/>}<span>{downloading?Math.round(progress*100)+'%':state?.complete?'已下載':'下載'}</span></button>{state?.selected&&<button className="pack-remove" disabled={!ready||!!busy} onClick={()=>send('PACK_REMOVE',p.id)} aria-label={'移除'+p.label+'離線資料'}><Trash2 size={14}/></button>}</div>;})}</div><button className="plain-button" onClick={()=>setAll(v=>!v)}>{all?'只看建議與已下載資料':'選擇其他縣市'}</button><p role="status">{message}</p><small>容量為各包上限；共用資料只儲存一份。法規包含相關函釋目錄，函釋全文需另下載。PDF 與外部附件需連線。</small></section>;
}
