import {useEffect,useState} from 'react';
import {ExternalLink,Download,Search,FolderPlus} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {practiceForms,practiceLaws,practiceSource,practiceObservedAt,loadPracticeDocument,downloadPracticeOriginal,practiceMatches,type PracticeDocument,type PracticeForm} from '../lib/practice-packs';
import {AddEvidenceButton} from './casebook';
import {makeSourceEvidence} from '../lib/casebook';
import {Highlight} from './law-navigation';
import './workspace-tools.css';

function FormItem({form,document,query,retry}:{form:PracticeForm;document?:PracticeDocument;query:string;retry:()=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function download(){setBusy(true);setError('');try{await downloadPracticeOriginal(form);}catch(e){setError(e instanceof Error?e.message:'書表尚未下載');}finally{setBusy(false);}}
 return <article className="practice-form"><div className="practice-form-meta">{form.group} · 官方書表 · {form.versionLabel}</div><h3><Highlight text={form.title} query={query}/></h3><div className="practice-form-actions"><button onClick={download} disabled={busy}><Download size={14}/>{busy?'準備原檔…':'下載原始 ODT'}</button><a href={form.source} target="_blank" rel="noreferrer">官方原檔<ExternalLink size={13}/></a><AddEvidenceButton label="加入案件" makeEvidence={async()=>{const doc=document||await loadPracticeDocument(form.id);return makeSourceEvidence({id:form.id,title:form.title,region:form.region,url:form.source,sourcePageURL:form.sourcePage,text:doc.text,sourceHash:form.sha256,observedAt:form.retrieved});}}/></div>{error&&<p className="practice-error" role="alert">{error}</p>}<details><summary>查看書表文字與來源</summary><dl className="practice-dates"><dt>來源擷取</dt><dd>{form.retrieved.split('T')[0]}</dd><dt>原檔識別</dt><dd><code>{form.sha256.slice(0,16)}</code></dd><dt>原檔格式</dt><dd>ODT · {Math.ceil(form.bytes/1024)} KB</dd></dl><p>{form.note}</p>{document?<pre><Highlight text={document.text} query={query}/></pre>:<p role="status">文字尚未載入。<button onClick={retry}>重新載入</button></p>}</details></article>;
}
export function PracticePacks({open,onOpenChange,onChoose,onCases,targetId=''}:{targetId?:string;open:boolean;onOpenChange:(v:boolean)=>void;onChoose:(id:string,article?:string)=>void;onCases:()=>void}){
 const [query,setQuery]=useState(''),[group,setGroup]=useState('全部'),[docs,setDocs]=useState<Record<string,PracticeDocument>>({}),[loading,setLoading]=useState(false),[failed,setFailed]=useState(0),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!open)return;const abort=new AbortController();setLoading(true);setFailed(0);Promise.allSettled(practiceForms.map(f=>loadPracticeDocument(f.id,abort.signal))).then(results=>{if(abort.signal.aborted)return;const got:Record<string,PracticeDocument>={};for(const result of results)if(result.status==='fulfilled')got[result.value.id]=result.value;setDocs(got);setFailed(results.filter(r=>r.status==='rejected').length);setLoading(false);});return()=>abort.abort();},[open,retry]);
 useEffect(()=>{if(open){setGroup('全部');setQuery(targetId?practiceForms.find(f=>f.id===targetId)?.title||'':'');}},[open,targetId]);
 const visible=practiceForms.filter(f=>(group==='全部'||f.group===group)&&practiceMatches(f,docs[f.id]?.text||'',query));
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="practice-dialog"><DialogTitle>新北簡易室裝資料包</DialogTitle><DialogDescription>官方書表、中央與地方依據，按辦理階段集中查找。</DialogDescription><div className="practice-intro"><p>收錄新北市官方清單標示 115/08/01 的 11 份書表，含住宅類（套房除外）、一般建築物、公有及私人文件。請依案件情況核對適用表單；本頁整理查找入口。</p><p>清單與原檔擷取：{practiceObservedAt.split('T')[0]}。書表標示日期與法規施行日期分開記錄。下載「新北市」離線包後可離線查閱本批書表，單檔 HTML 亦已內嵌。</p><a href={practiceSource} target="_blank" rel="noreferrer">核對官方最新作業表單<ExternalLink size={13}/></a><button onClick={onCases}><FolderPlus size={14}/>開啟案件資料夾</button></div><div className="practice-law-links"><h3>核對相關規定</h3>{practiceLaws.map(l=><button key={l.id} onClick={()=>{onOpenChange(false);onChoose(l.id,l.article);}}><strong>{l.label}</strong><span>{l.reason}</span></button>)}</div><p className="practice-scope">地方函釋仍需逐份核對：書表引用新北工建字第 1051778256 號等文號，原函及後續異動尚未完整收錄於此包。可由<a href="https://www.publicwork.ntpc.gov.tw/home.jsp?id=23" target="_blank" rel="noreferrer">工務局建照科法令專區</a>查核。</p><div className="practice-filters"><label><Search size={16}/><input aria-label="搜尋新北室裝書表" placeholder="搜尋書表名稱或內文" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="書表辦理階段" value={group} onChange={e=>setGroup(e.target.value)}>{['全部','施工許可','竣工與核備','文件清單'].map(g=><option key={g}>{g}</option>)}</select></div><p role="status">{loading?'正在載入書表文字…':`${visible.length} 份書表`}{failed>0&&` · ${failed} 份尚未下載，搜尋結果可能不完整`}</p>{failed>0&&<button onClick={()=>setRetry(v=>v+1)}>重新載入書表</button>}<div className="practice-list">{visible.map(form=><FormItem key={form.id} form={form} document={docs[form.id]} query={query} retry={()=>setRetry(v=>v+1)}/>)}</div>{!visible.length&&!loading&&<p>此篩選沒有符合的已收錄書表。{failed>0?'部分內文尚未載入，請連線後重試。':'可改用較短關鍵字查找。'}</p>}</DialogContent></Dialog>;
}
