import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import type {UniverseGraph,UniverseNode} from '@/lib/universe';

export type UniverseCanvasHandle={fit:(ids?:Set<string>,animate?:boolean)=>void;zoom:(factor:number)=>void;exportPNG:()=>void};
type Camera={x:number;y:number;k:number};
const palette=['#3b6278','#6b8271','#b1835e','#8b7390','#aa9253','#618e89','#8796a2','#b47c79'];
const categories=['建築與設計','使用與室內裝修','都市計畫與土地','都市更新與危老','消防與公共安全','農業與山坡地','環境與其他規範','目的事業與設立標準'];
export const universeColor=(n:UniverseNode)=>n.kind==='ruling'?'#9e978e':palette[Math.max(0,categories.indexOf(n.category))];
export const UniverseCanvas=forwardRef<UniverseCanvasHandle,{graph:UniverseGraph;focus:Set<string>|null;selected:string;onSelect:(id:string)=>void;onInteract:()=>void;onZoom:(percent:number)=>void}>(function UniverseCanvas({graph,focus,selected,onSelect,onInteract,onZoom},ref){
 const canvas=useRef<HTMLCanvasElement>(null),host=useRef<HTMLDivElement>(null),size=useRef({w:800,h:600}),camera=useRef<Camera>({x:400,y:300,k:.5}),frame=useRef(0),animation=useRef(0),drawRef=useRef(()=>{}),initialized=useRef(false);
 const callbacks=useRef({onSelect,onInteract,onZoom});callbacks.current={onSelect,onInteract,onZoom};
 const data=useRef({graph,focus,selected});data.current={graph,focus,selected};
 const pointers=useRef(new Map<number,{x:number;y:number}>()),gesture=useRef<{startX:number;startY:number;lastX:number;lastY:number;moved:boolean;distance:number}|null>(null);
 const [hover,setHover]=useState<{node:UniverseNode;x:number;y:number}|null>(null);
 const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 function schedule(){cancelAnimationFrame(frame.current);frame.current=requestAnimationFrame(()=>drawRef.current());}
 function change(next:Camera){camera.current=next;callbacks.current.onZoom(Math.round(next.k*100));schedule();}
 function moveTo(next:Camera,animate=false){cancelAnimationFrame(animation.current);if(!animate||reduced()){change(next);return;}const from={...camera.current},start=performance.now();const tick=(now:number)=>{const t=Math.min(1,(now-start)/260),e=1-Math.pow(1-t,3);change({x:from.x+(next.x-from.x)*e,y:from.y+(next.y-from.y)*e,k:from.k+(next.k-from.k)*e});if(t<1)animation.current=requestAnimationFrame(tick);};animation.current=requestAnimationFrame(tick);}
 function fit(ids?:Set<string>,animate=false){const nodes=data.current.graph.nodes.filter(n=>!ids||ids.has(n.id));if(!nodes.length)return;const xs=nodes.map(n=>n.x),ys=nodes.map(n=>n.y),left=Math.min(...xs)-50,right=Math.max(...xs)+50,top=Math.min(...ys)-50,bottom=Math.max(...ys)+50,{w,h}=size.current;const k=Math.min(1.8,Math.max(.08,Math.min((w-72)/(right-left),(h-90)/(bottom-top))));moveTo({x:w/2-(left+right)/2*k,y:h/2-(top+bottom)/2*k,k},animate);}
 function zoomAt(factor:number,x=size.current.w/2,y=size.current.h/2){cancelAnimationFrame(animation.current);const c=camera.current,k=Math.max(.08,Math.min(6,c.k*factor)),ratio=k/c.k;change({x:x-(x-c.x)*ratio,y:y-(y-c.y)*ratio,k});}
 function pick(x:number,y:number){const c=camera.current;let match:UniverseNode|null=null,best=Infinity;for(const n of data.current.graph.nodes){const d=Math.hypot(x-(n.x*c.k+c.x),y-(n.y*c.k+c.y)),r=Math.max(n.kind==='law'?8:4,n.radius*c.k+3);if(d<r){const score=d/r+(n.kind==='ruling'?.4:0);if(score<best){best=score;match=n;}}}return match;}
 function draw(){const el=canvas.current,ctx=el?.getContext('2d');if(!ctx)return;const {w,h}=size.current,dpr=Math.min(devicePixelRatio||1,2),c=camera.current,{graph:g,focus:f,selected:s}=data.current;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#f6f5f0';ctx.fillRect(0,0,w,h);
  ctx.fillStyle='#d8d9d2';const dot=32*c.k>18?32*c.k:32;for(let x=((c.x%dot)+dot)%dot;x<w;x+=dot)for(let y=((c.y%dot)+dot)%dot;y<h;y+=dot){ctx.beginPath();ctx.arc(x,y,.65,0,Math.PI*2);ctx.fill();}
  const pos=(n:UniverseNode)=>({x:n.x*c.k+c.x,y:n.y*c.k+c.y});
  for(const e of g.edges){const a=g.byId.get(e.from),b=g.byId.get(e.to);if(!a||!b)continue;const active=!f||(f.has(a.id)&&f.has(b.id)),p=pos(a),q=pos(b);if((p.x<0&&q.x<0)||(p.x>w&&q.x>w)||(p.y<0&&q.y<0)||(p.y>h&&q.y>h))continue;ctx.globalAlpha=active?(f?.7:e.kind==='basis'?.3:.13):.035;ctx.strokeStyle=e.kind==='basis'?'#577e86':e.kind==='citation'?'#a78258':'#b6ada0';ctx.lineWidth=e.kind==='basis'?(f?1.1:.7):.6;ctx.setLineDash(e.kind==='citation'?[3,4]:[]);const mx=(p.x+q.x)/2+(p.y-q.y)*.07,my=(p.y+q.y)/2+(q.x-p.x)*.07;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.quadraticCurveTo(mx,my,q.x,q.y);ctx.stroke();if(f&&active&&e.kind==='basis'&&c.k>.4){const angle=Math.atan2(q.y-my,q.x-mx),r=b.radius*c.k+3,x=q.x-Math.cos(angle)*r,y=q.y-Math.sin(angle)*r;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-Math.cos(angle-.5)*5,y-Math.sin(angle-.5)*5);ctx.lineTo(x-Math.cos(angle+.5)*5,y-Math.sin(angle+.5)*5);ctx.closePath();ctx.fillStyle='#577e86';ctx.fill();}}
  ctx.setLineDash([]);
  // Small ruling nodes first; law nodes stay easy to see and select.
  for(const kind of ['ruling','law'])for(const n of g.nodes){if(n.kind!==kind)continue;const p=pos(n);if(p.x<-50||p.x>w+50||p.y<-50||p.y>h+50)continue;const active=!f||f.has(n.id),isSelected=s===n.id,r=Math.max(kind==='law'?2.7:1.1,n.radius*c.k);ctx.globalAlpha=active?(kind==='law'?1:.52):.13;ctx.fillStyle=universeColor(n);if(isSelected){ctx.globalAlpha=1;ctx.beginPath();ctx.arc(p.x,p.y,r+12,0,Math.PI*2);ctx.fillStyle='#577e8615';ctx.fill();ctx.beginPath();ctx.arc(p.x,p.y,r+6,0,Math.PI*2);ctx.strokeStyle='#567f80';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=universeColor(n);}ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();if(kind==='law'&&n.region!=='中央'){ctx.fillStyle='#f6f5f0';ctx.fill();ctx.strokeStyle=universeColor(n);ctx.lineWidth=Math.max(1,r*.22);ctx.stroke();}}
  // Label collision checks keep overview and zoomed maps readable.
  const boxes:{x:number;y:number;w:number;h:number}[]=[];
  const labels=g.nodes.filter(n=>n.id===s||(n.kind==='law'&&(!f||f.has(n.id))&&(n.degree>6||c.k>1.2||(!!f&&c.k>.6)))).sort((a,b)=>Number(b.id===s)-Number(a.id===s)||b.degree-a.degree);
  for(const n of labels){const p=pos(n),isSelected=s===n.id;if(p.x<0||p.x>w||p.y<0||p.y>h)continue;const text=n.label.length>24?n.label.slice(0,23)+'…':n.label;ctx.font=(isSelected?'600 14px':'12px')+' "Noto Sans TC",system-ui,sans-serif';const tw=ctx.measureText(text).width,b={x:p.x-tw/2-5,y:p.y+Math.max(5,n.radius*c.k)+7,w:tw+10,h:20};if(!isSelected&&boxes.some(a=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y))continue;boxes.push(b);ctx.globalAlpha=.96;ctx.fillStyle='#f6f5f0';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.globalAlpha=1;ctx.fillStyle=isSelected?'#213d43':'#51626b';ctx.textAlign='center';ctx.fillText(text,p.x,b.y+14);}
  ctx.globalAlpha=1;
 }
 drawRef.current=draw;
 useImperativeHandle(ref,()=>({fit,zoom:(factor)=>zoomAt(factor),exportPNG:()=>{draw();const source=canvas.current;if(!source)return;const out=document.createElement('canvas');out.width=source.width;out.height=source.height+150;const ctx=out.getContext('2d');if(!ctx)return;ctx.fillStyle='#f6f5f0';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(source,0,110);ctx.fillStyle='#213d43';ctx.font='28px serif';ctx.fillText('openlawtw / 法規宇宙',36,48);ctx.font='16px sans-serif';ctx.fillText(`${graph.nodes.filter(n=>n.kind==='law').length} 部法規 · ${graph.edges.filter(e=>e.kind==='basis').length} 筆法源關係${selected?' · 聚焦 '+(graph.byId.get(selected)?.label??''):''}`,36,80);ctx.font='14px sans-serif';ctx.fillText('實線：法源／函釋引法　虛線：函釋互引。位置不代表位階；未連線不代表無關。',36,out.height-16);out.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='openlawtw-universe.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}}));
 useEffect(()=>{const el=host.current;if(!el)return;const observer=new ResizeObserver(()=>{const {width:w,height:h}=el.getBoundingClientRect();if(!w||!h)return;size.current={w,h};const dpr=Math.min(devicePixelRatio||1,2);if(canvas.current){canvas.current.width=Math.round(w*dpr);canvas.current.height=Math.round(h*dpr);}fit(undefined,false);initialized.current=true;});observer.observe(el);return()=>{observer.disconnect();cancelAnimationFrame(frame.current);cancelAnimationFrame(animation.current);};},[]);
 useEffect(()=>{if(initialized.current)fit(undefined,false);schedule();},[graph]);
 useEffect(schedule,[focus,selected]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();callbacks.current.onInteract();const r=el.getBoundingClientRect();zoomAt(Math.exp(-Math.max(-120,Math.min(120,e.deltaY))*.003),e.clientX-r.left,e.clientY-r.top);setHover(null);};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 return <div className="universe-canvas-host" ref={host}><canvas ref={canvas} aria-label="法規關係互動圖。拖曳平移，滾輪或雙指縮放；也可使用搜尋與右側清單選取節點。方向鍵移動，加減鍵縮放，Home 顯示全圖。" tabIndex={0}
 onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key))return;e.preventDefault();onInteract();cancelAnimationFrame(animation.current);const c=camera.current;if(e.key==='Home')fit();else if(e.key==='+'||e.key==='=')zoomAt(1.25);else if(e.key==='-')zoomAt(.8);else change({...c,x:c.x+(e.key==='ArrowLeft'?60:e.key==='ArrowRight'?-60:0),y:c.y+(e.key==='ArrowUp'?60:e.key==='ArrowDown'?-60:0)});}}
 onPointerDown={e=>{if(e.button!==0)return;onInteract();cancelAnimationFrame(animation.current);setHover(null);e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;pointers.current.set(e.pointerId,{x,y});if(pointers.current.size===1)gesture.current={startX:x,startY:y,lastX:x,lastY:y,moved:false,distance:0};else{const [a,b]=[...pointers.current.values()];if(gesture.current){gesture.current.moved=true;gesture.current.distance=Math.hypot(a.x-b.x,a.y-b.y);gesture.current.lastX=(a.x+b.x)/2;gesture.current.lastY=(a.y+b.y)/2;}}}}
 onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,g=gesture.current;if(!pointers.current.has(e.pointerId)||!g){if(e.pointerType==='mouse'){const node=pick(x,y);setHover(node?{node,x,y}:null);e.currentTarget.style.cursor=node?'pointer':'grab';}return;}pointers.current.set(e.pointerId,{x,y});if(pointers.current.size>1){const [a,b]=[...pointers.current.values()],dist=Math.hypot(a.x-b.x,a.y-b.y),mx=(a.x+b.x)/2,my=(a.y+b.y)/2;if(g.distance>0)zoomAt(dist/g.distance,mx,my);change({...camera.current,x:camera.current.x+mx-g.lastX,y:camera.current.y+my-g.lastY});g.distance=dist;g.lastX=mx;g.lastY=my;g.moved=true;}else{if(Math.hypot(x-g.startX,y-g.startY)>5)g.moved=true;if(g.moved)change({...camera.current,x:camera.current.x+x-g.lastX,y:camera.current.y+y-g.lastY});g.lastX=x;g.lastY=y;}}}
 onPointerUp={e=>{const g=gesture.current;if(!g||!pointers.current.has(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect();if(!g.moved&&pointers.current.size===1){const node=pick(e.clientX-r.left,e.clientY-r.top);if(node)onSelect(node.id);}pointers.current.delete(e.pointerId);if(pointers.current.size===0)gesture.current=null;else{const a=[...pointers.current.values()][0];g.lastX=a.x;g.lastY=a.y;g.moved=true;g.distance=0;}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);}}
 onLostPointerCapture={e=>{if(pointers.current.has(e.pointerId)){pointers.current.clear();gesture.current=null;}}} onPointerCancel={()=>{pointers.current.clear();gesture.current=null;}} onPointerLeave={()=>setHover(null)} onDoubleClick={e=>{const r=e.currentTarget.getBoundingClientRect();zoomAt(1.5,e.clientX-r.left,e.clientY-r.top);}}/>
 {hover&&<div className="universe-tooltip" style={{left:Math.max(12,Math.min(size.current.w-272,hover.x+16)),top:Math.max(12,Math.min(size.current.h-100,hover.y+14))}}><small>{hover.node.kind==='law'?hover.node.region+' · '+hover.node.category:'官方函釋'}</small><strong>{hover.node.label}</strong><span>點選查看關係</span></div>}</div>;
});
