import {candidateTerms,normalize,parseQuery} from './search.ts';
export type IndexRow={id:string;no?:string;articles?:string[]};
export type InvertedIndex={version:1;rows:IndexRow[];postings:Record<string,string>};
// Delta-varint postings keep common CJK grams compact. No original text is copied.
export function grams(text:string):string[]{const chars=Array.from(normalize(text)),out=new Set<string>();for(let i=0;i<chars.length;i++){out.add(chars[i]);if(i)out.add(chars[i-1]+chars[i]);}return [...out];}
function encode(ids:number[]){let last=0;const bytes:number[]=[];for(const id of ids){let d=id-last;last=id;while(d>=128){bytes.push((d&127)|128);d>>>=7;}bytes.push(d);}let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s);}
function decode(value:string|undefined):number[]{if(!value)return [];const bytes=atob(value),out:number[]=[];let n=0,shift=0,last=0;for(let i=0;i<bytes.length;i++){const b=bytes.charCodeAt(i);n|=(b&127)<<shift;if(b&128)shift+=7;else{last+=n;out.push(last);n=0;shift=0;}}return out;}
export function buildIndex(entries:{row:IndexRow;fields:string[]}[]):InvertedIndex{const postings=new Map<string,number[]>();entries.forEach((e,i)=>{for(const gram of new Set(e.fields.flatMap(grams))){let list=postings.get(gram);if(!list)postings.set(gram,list=[]);list.push(i);}});return {version:1,rows:entries.map(e=>e.row),postings:Object.fromEntries([...postings].sort(([a],[b])=>a<b?-1:1).map(([key,ids])=>[key,encode(ids)]))};}
const decoded=new WeakMap<InvertedIndex,Map<string,number[]>>();
function posting(index:InvertedIndex,key:string){let cache=decoded.get(index);if(!cache)decoded.set(index,cache=new Map());let p=cache.get(key);if(!p){p=decode(index.postings[key]);cache.set(key,p);}return p;}
function intersect(lists:number[][]):number[]{if(!lists.length)return [];lists.sort((a,b)=>a.length-b.length);let result=lists[0];for(const list of lists.slice(1)){const next:number[]=[];let a=0,b=0;while(a<result.length&&b<list.length){if(result[a]===list[b]){next.push(result[a]);a++;b++;}else if(result[a]<list[b])a++;else b++;}result=next;if(!result.length)break;}return result;}
function phrase(index:InvertedIndex,value:string):number[]{const chars=Array.from(normalize(value));const tokens=chars.length===1?chars:chars.slice(1).map((c,i)=>chars[i]+c);return intersect([...new Set(tokens)].map(g=>posting(index,g)));}
export function candidates(index:InvertedIndex,query:string):IndexRow[]{const groups=candidateTerms(query);const lists=groups.map(alternatives=>[...new Set(alternatives.flatMap(parts=>intersect(parts.map(p=>phrase(index,p)))))].sort((a,b)=>a-b));const ids=lists.length?intersect(lists):index.rows.map((_,i)=>i);const article=parseQuery(query).article;return ids.map(i=>index.rows[i]).filter(r=>!article||(r.no?normalize(r.no)===article:r.articles?.includes(article)));}
