// Real build bytes, deterministic Cache API, no network or browser internals.
import {readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash,webcrypto} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const root=new URL('../',import.meta.url).pathname,dist=join(root,'dist'),origin='https://openlawtw.vercel.app';
const source=await readFile(join(dist,'sw.js'),'utf8'),template=await readFile(join(root,'scripts/sw-template.js'),'utf8');
const manifest=JSON.parse(await readFile(join(dist,'data/manifest.json'),'utf8'));
const precache=JSON.parse(source.match(/const PRECACHE=(\[.*?\]),MANIFEST=/s)[1]);
const hash=b=>createHash('sha256').update(b).digest('hex'),key=x=>new URL(typeof x==='string'?x:x.url,origin).href;
const stores=new Map();let offline=false,failAt='',quotaAt='',network=[];
class RelativeRequest extends Request{constructor(x,init){super(new URL(typeof x==='string'?x:x.url,origin),init);}}
const caches={async open(name){if(!stores.has(name))stores.set(name,new Map());const map=stores.get(name);return {async put(req,res){if(name==='openlawtw-data-v2'&&key(req)===key(quotaAt||'/never'))throw Error('QuotaExceededError');map.set(key(req),res.clone());},async match(req){return map.get(key(req))?.clone();},async keys(){return [...map.keys()].map(url=>new RelativeRequest(url));},async delete(req){return map.delete(key(req));}};},async keys(){return [...stores.keys()];},async delete(name){return stores.delete(name);}};
async function fetchBytes(req){const path=new URL(typeof req==='string'?req:req.url,origin).pathname;network.push(path);if(offline)throw Error('offline');if(path===failAt)return new Response('wrong release bytes');try{return new Response(await readFile(join(dist,decodeURIComponent(path))));}catch{return new Response('',{status:404});}}
function worker(code,fetcher=fetchBytes){const events={},messages=[];let activated=0,skips=0;vm.runInNewContext(code,{URL,Request:RelativeRequest,Response,Uint8Array,crypto:webcrypto,caches,fetch:fetcher,self:{location:{origin},addEventListener:(n,f)=>events[n]=f,clients:{matchAll:async()=>[{postMessage:m=>messages.push(m)}],claim:async()=>{activated++;}},skipWaiting:async()=>{skips++;}}});return {messages,get activated(){return activated;},get skips(){return skips;},async fire(type,rest={}){const tasks=[];events[type]({...rest,source:{postMessage:m=>messages.push(m)},waitUntil:p=>tasks.push(p)});await Promise.all(tasks);},async get(path,mode){let value;events.fetch({request:{url:origin+path,method:'GET',mode},respondWith:p=>value=p});return value?await value:undefined;},external(){let captured=false;events.fetch({request:{url:'https://law.moj.gov.tw/',method:'GET'},respondWith:()=>captured=true});return captured;}};}
const old='openlawtw-v0.6-incomplete';await caches.open(old);await caches.open('unrelated-project');
const current=worker(source);await current.fire('install');assert.equal(current.skips,1);assert(stores.has(old));assert.equal(network.length,precache.length);assert(!network.some(p=>p.startsWith('/data/v2/')),'Fresh installation does not download the corpus');await current.fire('activate');assert(!stores.has(old));assert(stores.has('unrelated-project'));
let shellBytes=0;for(const entry of precache)shellBytes+=(await readFile(join(dist,decodeURIComponent(entry.url)))).length;assert(shellBytes<3*1024*1024,'Keep initial shell below 3 MiB');
assert(!precache.some(f=>/^\/laws\/(?!index\.html)[^/]+\.html$/.test(f.url)),'Do not precache every static law page');
assert.equal(current.external(),false);assert.equal(await current.get('/update.html','navigate'),undefined);
const lawFile=manifest.laws.D0070109;assert.equal((await (await current.get(lawFile.url)).json()).id,'D0070109');offline=true;let before=network.length;assert.match(await (await current.get('/','navigate')).text(),/openlawtw/);await current.get(lawFile.url);assert.match(await (await current.get('/laws/D0070109.html','navigate')).text(),/openlawtw/);assert.equal(await current.get('/laws/unknown-id.html','navigate'),undefined,'Unknown law routes do not become a misleading app-shell 200');assert.equal(network.length,before);offline=false;
const nt=manifest.packs.find(p=>p.id==='新北市'),tp=manifest.packs.find(p=>p.id==='臺北市');
await current.fire('message',{data:{type:'PACK_DOWNLOAD',packId:nt.id}});assert(current.messages.some(m=>m.type==='PACK_READY'&&m.packId===nt.id));const receipt=async()=>await (await (await caches.open('openlawtw-packs-v2')).match('/__openlawtw_packs__')).json();
assert.deepEqual((await receipt()).selected,[nt.id]);before=network.length;await current.fire('message',{data:{type:'PACK_DOWNLOAD',packId:nt.id}});assert.equal(network.length,before,'Repeat download reuses every stored shard');
failAt=tp.files.find(f=>!nt.files.some(shared=>shared.url===f.url)).url;await current.fire('message',{data:{type:'PACK_DOWNLOAD',packId:tp.id}});assert(current.messages.some(m=>m.type==='PACK_FAILED'&&m.packId===tp.id));assert.deepEqual((await receipt()).selected,[nt.id]);failAt='';await current.fire('message',{data:{type:'PACK_DOWNLOAD',packId:tp.id}});assert((await receipt()).selected.includes(tp.id));
offline=true;before=network.length;for(const f of [...nt.files,...tp.files])assert(await current.get(f.url));assert.equal(network.length,before,'Selected laws, headings and indexes are available with zero network');offline=false;
const third=manifest.packs.find(p=>p.id==='臺南市');quotaAt=third.files.find(f=>!nt.files.concat(tp.files).some(shared=>shared.url===f.url)).url;await current.fire('message',{data:{type:'PACK_DOWNLOAD',packId:third.id}});assert(!((await receipt()).selected.includes(third.id)));quotaAt='';
const cache=await caches.open('openlawtw-data-v2');await cache.delete(nt.files[0].url);await current.fire('message',{data:{type:'STATUS'}});assert.equal(current.messages.filter(m=>m.type==='PACK_STATUS').at(-1).packs.find(p=>p.id===nt.id).complete,false,'Evicted bytes are not labelled complete');await current.fire('message',{data:{type:'PACK_DOWNLOAD',packId:nt.id}});
await current.fire('message',{data:{type:'PACK_REMOVE',packId:tp.id}});assert(!((await receipt()).selected.includes(tp.id)));for(const f of nt.files)assert(await cache.match(f.url),'Removing a pack preserves shared files');
// Changed selected data is staged atomically. Failed releases preserve the active shell and receipts.
const changedFile=nt.files.find(f=>f.url.includes('/law-')),changed=JSON.parse(await readFile(join(dist,changedFile.url),'utf8'));changed.name+='（更新測試）';const updatedBytes=Buffer.from(JSON.stringify(changed)),newHash=hash(updatedBytes),replacement={url:changedFile.url.replace(changedFile.sha256,newHash),sha256:newHash,bytes:updatedBytes.length};
function replace(value){if(Array.isArray(value))return value.map(replace);if(value&&typeof value==='object'){if(value.url===changedFile.url)return replacement;return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,replace(v)]));}return value;}
const nextManifest=replace(manifest);nextManifest.release='test-next';
const nextSource=template.replace('__VERSION__','v0.7-test-next').replace('__PRECACHE__',JSON.stringify(precache)).replace('__MANIFEST__',JSON.stringify(nextManifest));
let breakUpdate=true;
const updateFetch=async req=>{const p=new URL(req.url,origin).pathname;if(p===replacement.url){network.push(p);return new Response(breakUpdate?'corrupt':updatedBytes);}return fetchBytes(req);};
const oldShell=[...stores.keys()].find(k=>k.startsWith('openlawtw-shell-'));const broken=worker(nextSource,updateFetch);await assert.rejects(broken.fire('install'),/Integrity mismatch/);assert.equal(broken.skips,0);assert(stores.has(oldShell));assert.equal((await receipt()).release,manifest.release);assert(!stores.has('openlawtw-shell-v0.7-test-next'));
breakUpdate=false;before=network.length;const next=worker(nextSource,updateFetch);await next.fire('install');assert.deepEqual(network.slice(before).filter(p=>p.startsWith('/data/v2/')),[replacement.url],'One changed data shard, not the entire selected collection');assert(stores.has(oldShell));await next.fire('activate');assert(!stores.has(oldShell));assert.equal((await receipt()).release,'test-next');assert(!await cache.match(changedFile.url));assert(await cache.match(replacement.url));
// A release that adds the shared count table reuses every existing selected data shard.
stores.clear();const previousManifest=structuredClone(manifest);delete previousManifest.rulingCounts;previousManifest.release='test-before-counts';previousManifest.files=previousManifest.files.filter(f=>f.url!==manifest.rulingCounts.url);
for(const pack of previousManifest.packs){pack.files=pack.files.filter(f=>f.url!==manifest.rulingCounts.url);pack.bytes=pack.files.reduce((sum,f)=>sum+f.bytes,0);}
const previousSource=template.replace('__VERSION__','test-before-counts').replace('__PRECACHE__',JSON.stringify(precache)).replace('__MANIFEST__',JSON.stringify(previousManifest));
const previous=worker(previousSource);await previous.fire('install');await previous.fire('activate');await previous.fire('message',{data:{type:'PACK_DOWNLOAD',packId:nt.id}});
before=network.length;const withCounts=worker(source);await withCounts.fire('install');assert.deepEqual(network.slice(before).filter(p=>p.startsWith('/data/v2/')),[manifest.rulingCounts.url]);await withCounts.fire('activate');
offline=true;before=network.length;assert((await (await withCounts.get(manifest.rulingCounts.url)).json()).D0070109.total>0);assert.equal(network.length,before);offline=false;
// A former full-offline v0.6 installation stays usable until all migrated packs succeed.
stores.clear();const legacy=await caches.open('openlawtw-v0.6-complete');await legacy.put('/data/laws.json',new Response('{}'));await legacy.put('/data/rulings.json',new Response('{}'));failAt=precache[0].url;const badLegacy=worker(source);await assert.rejects(badLegacy.fire('install'));assert(stores.has('openlawtw-v0.6-complete'));assert.equal(badLegacy.skips,0);failAt='';const migrated=worker(source);await migrated.fire('install');assert(stores.has('openlawtw-v0.6-complete'));await migrated.fire('activate');assert(!stores.has('openlawtw-v0.6-complete'));assert.equal((await receipt()).selected.length,manifest.packs.length);
offline=true;before=network.length;for(const pack of manifest.packs)for(const f of pack.files)assert(await migrated.get(f.url));assert.equal(network.length,before);
const pwa=JSON.parse(await readFile(join(dist,'manifest.webmanifest'),'utf8'));assert.equal(pwa.display,'standalone');assert(pwa.icons.some(i=>i.purpose==='maskable'));for(const i of pwa.icons){const b=await readFile(join(dist,i.src));assert.equal(b.toString('hex',0,8),'89504e470d0a1a0a');}
const html=await readFile(join(root,'openlawtw.html'),'utf8');assert(!/<script[^>]+src=/.test(html));assert(!/<link[^>]+rel="(?:stylesheet|manifest)"/.test(html));const inline=html.slice(html.indexOf('<script type="module">')+22,html.lastIndexOf('</script>'));const syntax=spawnSync(process.execPath,['--input-type=module','--check'],{input:inline,encoding:'utf8',maxBuffer:10*1024*1024});assert.equal(syntax.status,0,syntax.stderr);
const encoded=html.match(/const packed=Uint8Array\.from\(atob\("([A-Za-z0-9+/=]+)"\)/)[1],payload=JSON.parse(gunzipSync(Buffer.from(encoded,'base64')));for(const f of manifest.files)assert(payload[f.url],f.url);
console.log(JSON.stringify({initialShellFiles:precache.length,initialShellBytes:shellBytes,initialCorpusDownloads:0,packs:manifest.packs.length,fullMigration:'passed',atomicUpgrade:'passed',oneShardDelta:'passed',addedCountsUpgrade:'passed',corruptionRollback:'passed',quotaAndEviction:'passed',portableBytes:Buffer.byteLength(html)}));
