import {readFileSync} from 'node:fs';
import {splitLegalText,legalCharacterWidth} from '../lib/legal-tables.ts';
import {unitAnchor,lawHref} from '../lib/routes.ts';
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const safeJSON=value=>JSON.stringify(value).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
export function articleHTML(article,law,findReferences){
 function inline(text){let html='',at=0;for(const ref of findReferences(text,law)){html+=escapeHTML(text.slice(at,ref.start))+`<a class="legal-reference" href="${escapeHTML(lawHref(ref.law.id,ref.article,ref.unit))}" title="${escapeHTML(ref.law.name+' '+ref.article+' · 本庫快照')}">${escapeHTML(text.slice(ref.start,ref.end))}</a>`;at=ref.end;}return html+escapeHTML(text.slice(at));}
 function formatted(text){return splitLegalText(text).map(block=>{
  if(block.kind==='text')return inline(block.text);
  const label=escapeHTML(law.name+' '+article.no),raw='<pre class="legal-table-raw">'+[...block.text].map(c=>c==='\n'?'\n':`<span style="width:${legalCharacterWidth(c)/2}em">${escapeHTML(c)}</span>`).join('')+'</pre>';
  const scroll=body=>`<section class="legal-table-scroll" role="region" aria-label="${label}表格，可左右捲動" tabindex="0">${body}</section>`;
  const table=block.table?`<table class="legal-data-table"><caption class="legal-table-caption">${label}官方條文表格</caption><tbody>${block.table.rows.map(row=>'<tr>'+row.map(cell=>`<td rowspan="${cell.rowSpan}" colspan="${cell.colSpan}">${inline(cell.text)}</td>`).join('')+'</tr>').join('')}</tbody></table>`:'';
  return `<figure class="legal-table-block" data-source-start="${block.start}" data-source-end="${block.end}"><figcaption>${label} · ${table?'表格':'原文圖表'}<span>寬表可左右捲動</span></figcaption>${table?scroll(table)+`<details class="legal-table-source"><summary>核對原始文字表格</summary>${scroll(raw)}</details>`:scroll(raw)}</figure>`;
 }).join('');}
 function range(start,end,units){let html='',at=start;for(const unit of units){html+=formatted(article.text.slice(at,unit.start))+`<span id="${escapeHTML(unitAnchor(unit.id))}">`+range(unit.start,unit.end,unit.children)+'</span>';at=unit.end;}return html+formatted(article.text.slice(at,end));}
 return `<section id="${escapeHTML(article.anchor)}" class="static-article"><h2>${escapeHTML(article.no)}</h2><div class="static-text">${range(0,article.text.length,article.structure?.units||[])}</div></section>`;
}
export const staticStyles=readFileSync(new URL('../components/legal-table.css',import.meta.url),'utf8')+`
*{box-sizing:border-box}.static-page{height:100dvh;overflow:auto;background:#fafbf9;color:#253440;font:15px/1.8 system-ui,sans-serif;padding:36px max(24px,calc((100% - 940px)/2)) 80px}.static-page a{color:inherit;text-underline-offset:4px}.static-page nav{display:flex;justify-content:space-between;gap:16px;padding-bottom:28px;border-bottom:1px solid #dfe4e5}.static-brand{font-weight:700;letter-spacing:-.6px;font-size:22px;text-decoration:none}.static-page header{padding:36px 0 28px}.static-page h1{font:500 clamp(28px,4vw,40px)/1.5 Georgia,'Noto Serif TC',serif;letter-spacing:.01em;margin:8px 0 20px}.static-kicker{font-size:12px;color:#677b88;letter-spacing:.05em}.static-facts{font-size:13px;color:#536772;display:flex;gap:8px 24px;flex-wrap:wrap}.static-source{margin-top:18px}.static-note{font-size:12px;color:#6c7880;padding:16px 0}.static-article{display:grid;grid-template-columns:100px minmax(0,1fr);gap:20px;border-top:1px solid #dfe4e5;padding:24px 0;scroll-margin-top:24px}.static-article h2{font:500 13px/2 system-ui;margin:0;color:#657781}.static-text{white-space:pre-wrap;overflow-wrap:anywhere;font:18px/1.95 Georgia,'Noto Serif TC',serif}.static-text [id]{scroll-margin-top:24px}.static-text :target,.static-article:target{background:#fff6df}.static-page details{border-top:1px solid #dfe4e5;padding:14px 0}.static-page summary{cursor:pointer;display:list-item;font-weight:600}.static-page ul{padding-left:20px}.static-page li{margin:8px 0}.static-page li small{color:#7b858b;margin-left:12px}.static-chapter{font-size:13px;color:#74818a;margin:22px 0 8px}.static-page .legal-reference{text-decoration:underline dotted;text-decoration-color:#95a9b6}.static-page .legal-reference:hover{text-decoration-style:solid;color:#315c76}.static-footer{margin-top:30px;border-top:1px solid #dfe4e5;padding-top:20px;font-size:12px;color:#74818a}@media(max-width:600px){.static-page{padding:22px 24px 60px}.static-article{display:block}.static-article h2{margin-bottom:12px}.static-page nav{font-size:12px}.static-page header{padding-top:28px}}
`;
